.pragma library
// SPDX-FileCopyrightText: 2026 Denis Robel
// SPDX-License-Identifier: GPL-3.0-or-later

// Names of settings and categories, generated from OpenSCQ30 v2.12.0's
// lib/i18n/*/openscq30-lib.ftl (GPL-3.0-or-later), plus SailSCQ's own
// translations of the categories and sound modes for all Sailfish OS languages.
// Keys are the camelCase ids used by the openscq30 CLI.

var names = {
 "bg": {
  "ambientSoundMode": "Режим на околния звук",
  "buttonConfiguration": "Настройки на бутоните",
  "case": "Кутия за зареждане",
  "deviceInformation": "Информация за устройството",
  "dualConnections": "Двойна връзка",
  "equalizer": "Еквалайзер",
  "equalizerImportExport": "Импорт/експорт на еквалайзера",
  "general": "Общи",
  "lights": "Осветление",
  "limitHighVolume": "Ограничение на звука",
  "listeningMode": "Режим на слушане",
  "local": "Локално",
  "miscellaneous": "Разни",
  "noiseCanceling": "Шумопотискане",
  "normal": "Нормален",
  "soundModes": "Звукови режими",
  "transparency": "Прозрачност"
 },
 "bn": {
  "ambientSoundMode": "পারিপার্শ্বিক শব্দ মোড",
  "buttonConfiguration": "বোতাম কনফিগারেশন",
  "case": "চার্জিং কেস",
  "deviceInformation": "ডিভাইসের তথ্য",
  "dualConnections": "ডুয়াল সংযোগ",
  "equalizer": "ইকুয়ালাইজার",
  "equalizerImportExport": "ইকুয়ালাইজার আমদানি/রপ্তানি",
  "general": "সাধারণ",
  "lights": "আলো",
  "limitHighVolume": "ভলিউম সীমা",
  "listeningMode": "শোনার মোড",
  "local": "স্থানীয়",
  "miscellaneous": "বিবিধ",
  "noiseCanceling": "নয়েজ ক্যান্সেলিং",
  "none": "নেই",
  "normal": "স্বাভাবিক",
  "soundModes": "সাউন্ড মোড",
  "transparency": "স্বচ্ছতা"
 },
 "cs": {
  "ambientSoundMode": "Režim okolního zvuku",
  "buttonConfiguration": "Nastavení tlačítek",
  "case": "Nabíjecí pouzdro",
  "deviceInformation": "Informace o zařízení",
  "dualConnections": "Dvojí připojení",
  "equalizer": "Ekvalizér",
  "equalizerImportExport": "Import/export ekvalizéru",
  "general": "Obecné",
  "lights": "Osvětlení",
  "limitHighVolume": "Omezení hlasitosti",
  "listeningMode": "Režim poslechu",
  "local": "Místní",
  "miscellaneous": "Různé",
  "noiseCanceling": "Potlačení hluku",
  "normal": "Normální",
  "soundModes": "Zvukové režimy",
  "transparency": "Propustnost"
 },
 "da": {
  "ambientSoundMode": "Omgivelseslydtilstand",
  "buttonConfiguration": "Knapkonfiguration",
  "case": "Opladningsetui",
  "deviceInformation": "Enhedsoplysninger",
  "dualConnections": "Dobbeltforbindelse",
  "equalizer": "Equalizer",
  "equalizerImportExport": "Equalizer-import/-eksport",
  "general": "Generelt",
  "lights": "Lys",
  "limitHighVolume": "Lydstyrkebegrænsning",
  "listeningMode": "Lyttetilstand",
  "local": "Lokal",
  "miscellaneous": "Diverse",
  "noiseCanceling": "Støjreduktion",
  "normal": "Normal",
  "soundModes": "Lydtilstande",
  "transparency": "Gennemsigtighed"
 },
 "de": {
  "acoustic": "Akustisch",
  "adaptive": "Adaptiv",
  "adaptiveNoiseCanceling": "Adaptive Geräuschunterdrückung",
  "adaptiveNoiseCancelingSensitivityLevel": "Adaptive Geräuschunterdrückung - Empfindlichkeitsniveau",
  "ambientSoundMode": "Umgebungsgeräusch-Modus",
  "autoPowerOff": "Automatisches Ausschalten",
  "bassBooster": "Bassverstärker",
  "bassReducer": "Bassreduzierer",
  "batteryLevel": "Batteriestand",
  "batteryLevelLeft": "Batteriestand (links)",
  "batteryLevelRight": "Batteriestand (rechts)",
  "bus": "Bus",
  "buttonConfiguration": "Tastenkonfiguration",
  "car": "Auto",
  "caseBatteryLevel": "Batteriestand (Hülle)",
  "charging": "Lädt",
  "classical": "Klassisch",
  "connected": "Verbunden",
  "custom": "Benutzerdefiniert",
  "customEqualizerProfile": "Benutzerdefiniertes Profil",
  "customNoiseCanceling": "Benutzerdefinierte Geräuschunterdrückung",
  "customProfile": "Benutzerdefiniertes Profil",
  "dance": "Tanz",
  "deviceInformation": "Geräteinformation",
  "disabled": "Deaktiviert",
  "disconnected": "Getrennt",
  "doublePress": "Doppeldruck",
  "electronic": "Elektronisch",
  "environmentDetection": "Umgebungserkennung",
  "equalizer": "Equalizer",
  "equalizerImportExport": "Equalizer Import/Export",
  "exportCustomEqualizerProfiles": "Benutzerdefinierte Profile exportieren",
  "firmwareVersion": "Firmware-Version",
  "firmwareVersionLeft": "Firmware-Version (links)",
  "firmwareVersionRight": "Firmware-Version (rechts)",
  "fullyTransparent": "Voll transparent",
  "gamingMode": "Game-Modus",
  "general": "Allgemein",
  "highNoise": "Hohe Lautstärke",
  "hipHop": "Hip Hop",
  "hostDevice": "Host-Gerät",
  "importCustomEqualizerProfiles": "Benutzdefinierte Profile importieren",
  "importCustomEqualizerProfilesConfirm": "Dies wird existierende Profile mit dem gleichen Namen überschreiben.",
  "indoor": "Innenbereich",
  "isCharging": "Wird geladen",
  "isChargingLeft": "Wird geladen (links)",
  "isChargingRight": "Wird geladen (rechts)",
  "jazz": "Jazz",
  "left": "Links",
  "leftDoublePress": "Doppeldruck links",
  "leftLongPress": "Langer Druck links",
  "leftSinglePress": "Einzeldruck links",
  "leftTriplePress": "Dreifachdruck links",
  "lounge": "Lounge",
  "lowNoise": "Niedrige Lautstärke",
  "manual": "Manuell",
  "manualNoiseCanceling": "Manuelle Geräuschunterdrückung",
  "manualTransparency": "Manuelle Transparenz",
  "mediumNoise": "Mittlere Lautstärke",
  "miscellaneous": "Verschiedenes",
  "moderate": "Mittel",
  "nextSong": "Nächstes Lied",
  "no": "Nein",
  "noiseCanceling": "Geräuschunterdrückung",
  "noiseCancelingMode": "Geräuschunterdrückungs-Modus",
  "none": "Nichts",
  "normal": "Normal",
  "notCharging": "Lädt nicht",
  "outdoor": "Außenbereich",
  "piano": "Klavier",
  "playPause": "Wiedergabe/Pause",
  "podcast": "Podcast",
  "pop": "Pop",
  "presetEqualizerProfile": "Voreinstellungs-Profil",
  "presetProfile": "Voreinstellungs-Profil",
  "previousSong": "Vorheriges Lied",
  "resetButtonsToDefault": "Tasten auf Standardeinstellungen zurücksetzen",
  "right": "Rechts",
  "rightDoublePress": "Doppeldruck rechts",
  "rightLongPress": "Langer Druck rechts",
  "rightSinglePress": "Einzeldruck rechts",
  "rightTriplePress": "Dreifachdruck rechts",
  "rock": "Rock",
  "serialNumber": "Seriennummer",
  "singlePress": "Einzeldruck",
  "smallSpeakers": "Kleine Lautsprecher",
  "soundModes": "Sound-Modi",
  "strong": "Stark",
  "touchTone": "Berührungston",
  "train": "Zug",
  "transparency": "Transparenz",
  "transparencyMode": "Transparenz-Modus",
  "transport": "Transport",
  "transportation": "Transport",
  "trebleBooster": "Höhenverstärker",
  "trebleReducer": "Höhenreduzierer",
  "vocalMode": "Stimmen-Modus",
  "voiceAssistant": "Sprachassistent",
  "volume": "Lautstärke",
  "volumeAdjustments": "Lautstärkeregelung",
  "volumeDown": "Lautstärke verringern",
  "volumeUp": "Lautstärke erhöhen",
  "weak": "Schwach",
  "windNoiseDetected": "Windgeräusche erkannt",
  "windNoiseSuppression": "Windgeräuschdämpfung",
  "yes": "Ja"
 },
 "el": {
  "ambientSoundMode": "Λειτουργία ήχου περιβάλλοντος",
  "buttonConfiguration": "Ρύθμιση κουμπιών",
  "case": "Θήκη φόρτισης",
  "deviceInformation": "Πληροφορίες συσκευής",
  "dualConnections": "Διπλή σύνδεση",
  "equalizer": "Ισοσταθμιστής",
  "equalizerImportExport": "Εισαγωγή/εξαγωγή ισοσταθμιστή",
  "general": "Γενικά",
  "lights": "Φωτισμός",
  "limitHighVolume": "Όριο έντασης",
  "listeningMode": "Λειτουργία ακρόασης",
  "local": "Τοπικά",
  "miscellaneous": "Διάφορα",
  "noiseCanceling": "Ακύρωση θορύβου",
  "normal": "Κανονική",
  "soundModes": "Λειτουργίες ήχου",
  "transparency": "Διαφάνεια"
 },
 "en": {
  "acoustic": "Acoustic",
  "adaptive": "Adaptive",
  "adaptiveNoiseCanceling": "Adaptive Noise Canceling",
  "adaptiveNoiseCancelingSensitivityLevel": "Adaptive Noise Canceling Sensitivity Level",
  "airPressure": "Air Pressure",
  "airplaneMode": "Airplane Mode",
  "alarms": "Alarms",
  "ambientSoundMode": "Ambient Sound Mode",
  "ancPersonalizedToEarCanal": "ANC Personalized to Ear Canal",
  "atmospheric": "Atmospheric",
  "autoLightsOffMinutes": "Auto Lights Off (minutes)",
  "autoPlayPause": "Auto Play/Pause",
  "autoPowerOff": "Auto Power Off",
  "autoPowerOffPrompt": "Auto Power Off Prompt",
  "autoStopTimer": "Auto Stop Timer",
  "autoStopTimerDuration": "Auto Stop Timer Duration",
  "automaticUpdate": "Automatic Update",
  "balanced": "Balanced",
  "bassBooster": "Bass Booster",
  "bassOff": "Bass Off",
  "bassReducer": "Bass Reducer",
  "bassUp": "Bass Up",
  "batteryLevel": "Battery Level",
  "batteryLevelLeft": "Battery Level (Left)",
  "batteryLevelRight": "Battery Level (Right)",
  "bloom": "Bloom",
  "bluetooth": "Bluetooth",
  "breathing": "Breathing",
  "bus": "Bus",
  "buttonConfiguration": "Button Configuration",
  "buttonsEnabled": "Buttons Enabled",
  "car": "Car",
  "case": "Case",
  "caseBatteryLevel": "Case Battery Level",
  "caseFirmwareVersion": "Case Firmware Version",
  "caseLanguage": "Case Language",
  "caseSerialNumber": "Case Serial Number",
  "changeMode": "Change Mode",
  "charging": "Charging",
  "classic": "Classic",
  "classical": "Classical",
  "connected": "Connected",
  "custom": "Custom",
  "customEqualizerProfile": "Custom Profile",
  "customNoiseCanceling": "Custom Noise Canceling",
  "customProfile": "Custom Profile",
  "dance": "Dance",
  "dbLimit": "DB Limit",
  "dbRefreshRate": "DB Refresh Rate",
  "deep": "Deep",
  "defaultListeningMode": "Default Listening Mode",
  "deviceInformation": "Device Information",
  "disabled": "Disabled",
  "disconnected": "Disconnected",
  "dolbyAudio": "Dolby Audio",
  "doublePress": "Double Press",
  "dualConnections": "Dual Connections",
  "dualConnectionsDevices": "Dual Connections Devices",
  "easyChat": "Easy Chat",
  "easyChatWaitTime": "Easy Chat Wait Time",
  "electronic": "Electronic",
  "enabled": "Enabled",
  "environmentDetection": "Environment Detection",
  "equalizer": "Equalizer",
  "equalizerImportExport": "Equalizer Import/Export",
  "exportCustomEqualizerProfiles": "Export Custom Profiles",
  "exportCustomEqualizerProfilesOutput": "Export Custom Profiles Output",
  "findDevice": "Find Device",
  "firmest": "Firmest",
  "firmwareVersion": "Firmware Version",
  "firmwareVersionLeft": "Firmware Version (Left)",
  "firmwareVersionRight": "Firmware Version (Right)",
  "fixed": "Fixed",
  "flash": "Flash",
  "flat": "Flat",
  "friday": "Friday",
  "fullyTransparent": "Fully Transparent",
  "gaming": "Gaming",
  "gamingMode": "Gaming Mode",
  "general": "General",
  "glow": "Glow",
  "headTracking": "Head Tracking",
  "heavy": "Heavy",
  "highNoise": "High Noise",
  "hipHop": "Hip Hop",
  "hostDevice": "Host Device",
  "immersiveExperience": "Immersive Experience",
  "importCustomEqualizerProfiles": "Import Custom Profiles",
  "importCustomEqualizerProfilesConfirm": "This will overwrite existing profiles that share the same names.",
  "incomingCallsDuringBluetoothMode": "Incoming Calls During Bluetooth Mode",
  "indoor": "Indoor",
  "isCharging": "Is Charging",
  "isChargingLeft": "Is Charging (Left)",
  "isChargingRight": "Is Charging (Right)",
  "jazz": "Jazz",
  "latin": "Latin",
  "ldac": "LDAC",
  "left": "Left",
  "leftDoublePress": "Left Double Press",
  "leftLongPress": "Left Long Press",
  "leftSinglePress": "Left Single Press",
  "leftSlideDown": "Left Slide Down",
  "leftSlideUp": "Left Slide Up",
  "leftTriplePress": "Left Triple Press",
  "lightOn": "Light On",
  "lights": "Lights",
  "lightsBrightness": "Colorful Lights Brightness",
  "lightsColor": "Colorful Lights Color",
  "lightsEnabled": "Colorful Lights Enabled",
  "lightsMode": "Colorful Lights Mode",
  "limitHighVolume": "Limit High Volume",
  "limitHighVolumeDbLimit": "DB Limit",
  "limitHighVolumeRefreshRate": "DB Refresh Rate",
  "listeningMode": "Listening Mode",
  "listeningModePrompt": "Listening Mode Prompt",
  "local": "Local",
  "lounge": "Lounge",
  "lowBatteryPrompt": "Low Battery Prompt",
  "lowNoise": "Low Noise",
  "manual": "Manual",
  "manualNoiseCanceling": "Manual Noise Canceling",
  "manualTransparency": "Manual Transparency",
  "manualUpdate": "Manual Update",
  "medium": "Medium",
  "mediumNoise": "Medium Noise",
  "miscellaneous": "Miscellaneous",
  "moderate": "Moderate",
  "monday": "Monday",
  "movie": "Movie",
  "movieMode": "Movie Mode",
  "multiScene": "Multi-Scene",
  "multiSceneNoiseCanceling": "Multi-Scene Noise Canceling",
  "music": "Music",
  "musicFollows": "Music Follows",
  "nature": "Nature",
  "nextSong": "Next Song",
  "no": "No",
  "noiseCanceling": "Noise Canceling",
  "noiseCancelingMode": "Noise Canceling Mode",
  "noiseCancelingModeInCycle": "Noise Canceling Mode in Cycle",
  "noiseCancelingPrompt": "Noise Canceling Prompt",
  "none": "None",
  "normal": "Normal",
  "normalModeInCycle": "Normal Mode in Cycle",
  "notCharging": "Not Charging",
  "original": "Original",
  "outdoor": "Outdoor",
  "piano": "Piano",
  "plane": "Plane",
  "playPause": "Play Pause",
  "podcast": "Podcast",
  "pop": "Pop",
  "powerOff": "Power Off",
  "presetEqualizerProfile": "Preset Profile",
  "presetProfile": "Preset Profile",
  "pressureSensitivity": "Pressure Sensitivity",
  "previousSong": "Previous Song",
  "realTime": "Real Time",
  "realTimeAdaptiveNoiseCanceling": "Real Time Adaptive Noise Canceling",
  "remoteCamera": "Remote Camera",
  "resetButtonsToDefault": "Reset Buttons to Default",
  "rhythm": "Rhythm",
  "right": "Right",
  "rightDoublePress": "Right Double Press",
  "rightLongPress": "Right Long Press",
  "rightSinglePress": "Right Single Press",
  "rightSlideDown": "Right Slide Down",
  "rightSlideUp": "Right Slide Up",
  "rightTriplePress": "Right Triple Press",
  "rnb": "RnB",
  "rock": "Rock",
  "saturday": "Saturday",
  "sendPacket": "Send Packet",
  "serialNumber": "Serial Number",
  "sideTone": "Side Tone",
  "singlePress": "Single Press",
  "smallSpeakers": "Small Speakers",
  "softest": "Softest",
  "soundLeakCompensation": "Sound Leak Compensation",
  "soundModes": "Sound Modes",
  "soundcoreA3004": "Soundcore Q20I",
  "soundcoreA3027": "Soundcore Life Q35",
  "soundcoreA3028": "Soundcore Q30 / Life Q30",
  "soundcoreA3029": "Soundcore Life Tune",
  "soundcoreA3030": "Soundcore Life Tune Pro",
  "soundcoreA3031": "Soundcore Vortex",
  "soundcoreA3033": "Soundcore Life 2 Neo",
  "soundcoreA3035": "Soundcore Space One",
  "soundcoreA3040": "Soundcore Space Q45",
  "soundcoreA3062": "Soundcore Space One Pro",
  "soundcoreA3116": "Soundcore Motion+",
  "soundcoreA3876": "Soundcore V20i",
  "soundcoreA3909": "Soundcore Liberty 2 Pro",
  "soundcoreA3926": "Soundcore Life Dot 2S",
  "soundcoreA3930": "Soundcore Liberty 2 Pro+",
  "soundcoreA3931": "Soundcore Life Dot 2 NC",
  "soundcoreA3933": "Soundcore Life Note 3",
  "soundcoreA3935": "Soundcore Life A2 NC",
  "soundcoreA3936": "Soundcore Space A40",
  "soundcoreA3939": "Soundcore Life P3",
  "soundcoreA3944": "Soundcore Life P2 Mini",
  "soundcoreA3945": "Soundcore Life Note 3S",
  "soundcoreA3947": "Soundcore Liberty 4 NC",
  "soundcoreA3948": "Soundcore A20i",
  "soundcoreA3949": "Soundcore P20i / P25i / R50i",
  "soundcoreA3951": "Soundcore Liberty Air 2 Pro",
  "soundcoreA3952": "Soundcore Liberty 3 Pro",
  "soundcoreA3954": "Soundcore Liberty 4 Pro",
  "soundcoreA3955": "Soundcore P40i",
  "soundcoreA3957": "Soundcore Liberty 5",
  "soundcoreA3959": "Soundcore P30i / R50i NC",
  "soundcoreA3968": "Soundcore Sport X20",
  "soundcoreD1101": "Soundcore C50i",
  "soundcoreD1202": "Soundcore P31i",
  "soundcoreD1202c": "Soundcore R60i NC",
  "soundcoreD1301": "Soundcore Sleep A30",
  "soundcoreDevelopment": "Soundcore Development Information",
  "soundcoreSignature": "Soundcore Signature",
  "spatialAudio": "Spatial Audio",
  "spatialAudioMode": "Spatial Audio Mode",
  "spatialAudioMusicMode": "Spatial Audio Music Mode",
  "spokenWord": "Spoken Word",
  "stateUpdatePacket": "State Update Packet",
  "strong": "Strong",
  "sunday": "Sunday",
  "surroundSound": "Surround Sound",
  "talkMode": "Talk Mode",
  "thursday": "Thursday",
  "touchLock": "Touch Lock",
  "touchTone": "Touch Tone",
  "train": "Train",
  "transparency": "Transparency",
  "transparencyMode": "Transparency Mode",
  "transparencyModeInCycle": "Transparency Mode in Cycle",
  "transport": "Transport",
  "transportation": "Transportation",
  "transportationMode": "Transportation Mode",
  "trebleBooster": "Treble Booster",
  "trebleReducer": "Treble Reducer",
  "tuesday": "Tuesday",
  "twsStatus": "True Wireless (TWS) Status",
  "vocalMode": "Vocal Mode",
  "voice": "Voice",
  "voiceAssistant": "Voice Assistant",
  "voicePrompt": "Voice Prompt",
  "volume": "Volume",
  "volumeAdjustments": "Volume Adjustments",
  "volumeBalance": "Volume Balance",
  "volumeBooster": "Volume Booster",
  "volumeDown": "Volume Down",
  "volumeUp": "Volume Up",
  "weak": "Weak",
  "wearingDetection": "Wearing Detection",
  "wearingTone": "Wearing Tone",
  "wednesday": "Wednesday",
  "windNoiseDetected": "Wind Noise Detected",
  "windNoiseSuppression": "Wind Noise Suppression",
  "yes": "Yes"
 },
 "es": {
  "acoustic": "Acústico",
  "adaptive": "Adaptativo",
  "adaptiveNoiseCanceling": "Cancelación adaptativa de ruido",
  "adaptiveNoiseCancelingSensitivityLevel": "Nivel de sensibilidad de la cancelación adaptativa de ruido",
  "airPressure": "Presión atmosférica",
  "airplaneMode": "Modo avión",
  "alarms": "Alarmas",
  "ambientSoundMode": "Modo de sonido ambiente",
  "ancPersonalizedToEarCanal": "Cancelación activa de ruido personalizada para el canal auditivo",
  "atmospheric": "Atmosférico",
  "autoLightsOffMinutes": "Apagado automático de luces (minutos)",
  "autoPlayPause": "Reproducción/pausa automática",
  "autoPowerOff": "Apagado automático",
  "autoPowerOffPrompt": "Mensaje de autoapagado",
  "autoStopTimer": "Temporizador de apagado automático",
  "autoStopTimerDuration": "Duración del temporizador de autoapagado",
  "automaticUpdate": "Actualización automática",
  "balanced": "Equilibrado",
  "bassBooster": "Potenciador de graves",
  "bassOff": "Reduce los bajos",
  "bassReducer": "Reductor de graves",
  "bassUp": "Sube los bajos",
  "batteryLevel": "Nivel de batería",
  "batteryLevelLeft": "Nivel de batería (izquierda)",
  "batteryLevelRight": "Nivel de batería (derecha)",
  "bloom": "Resplandor",
  "bluetooth": "Bluetooth",
  "breathing": "Parpadeo",
  "bus": "Autobús",
  "buttonConfiguration": "Configuración de botones",
  "buttonsEnabled": "Botones habilitados",
  "car": "Coche",
  "case": "Caja",
  "caseBatteryLevel": "Nivel de batería de la funda",
  "caseFirmwareVersion": "Versión del firmware de la carcasa",
  "caseLanguage": "Idioma de la funda",
  "caseSerialNumber": "Número de serie de la caja",
  "changeMode": "Modificar modo",
  "charging": "Está cargando",
  "classic": "Clásica",
  "classical": "Clásico",
  "connected": "Conectado",
  "custom": "Personalizado",
  "customEqualizerProfile": "Perfil personalizado",
  "customNoiseCanceling": "Cancelación de ruido personalizada",
  "customProfile": "Perfil personalizado",
  "dance": "Dance",
  "dbLimit": "Límite de decibelios",
  "dbRefreshRate": "Tasa de refresco de los decibelios",
  "deep": "Deep House",
  "defaultListeningMode": "Modo ambiente predeterminado",
  "deviceInformation": "Información del dispositivo",
  "disabled": "Desactivado",
  "disconnected": "Desconectado",
  "dolbyAudio": "Dolby Audio",
  "doublePress": "Doble pulsación",
  "dualConnections": "Conexiones duales",
  "dualConnectionsDevices": "Dispositivos de doble conexión",
  "easyChat": "EasyChatbot",
  "easyChatWaitTime": "Tiempo de espera en EasyChatbot",
  "electronic": "Electrónica",
  "enabled": "Activado",
  "environmentDetection": "Detección del entorno",
  "equalizer": "Ecualizador",
  "equalizerImportExport": "Importar/exportar ecualizador",
  "exportCustomEqualizerProfiles": "Exportar perfiles personalizados",
  "exportCustomEqualizerProfilesOutput": "Exportar los perfiles personalizados generados",
  "findDevice": "Buscar dispositivo",
  "firmest": "Firmes",
  "firmwareVersion": "Versión del firmware",
  "firmwareVersionLeft": "Versión del firmware (izquierda)",
  "firmwareVersionRight": "Versión del firmware (derecha)",
  "fixed": "Corregido",
  "flash": "Flash",
  "flat": "Afinación",
  "friday": "Viernes",
  "fullyTransparent": "Totalmente transparente",
  "gaming": "Juego",
  "gamingMode": "Modo de juego",
  "general": "General",
  "glow": "Brillo",
  "headTracking": "Seguimiento de la cabeza",
  "heavy": "Heavy",
  "highNoise": "Ruido alto",
  "hipHop": "Hip Hop",
  "hostDevice": "Host del dispositivo",
  "immersiveExperience": "Experiencia inmersiva",
  "importCustomEqualizerProfiles": "Importar perfiles personalizados",
  "importCustomEqualizerProfilesConfirm": "Esto sobrescribirá los perfiles existentes que compartan el mismo nombre.",
  "incomingCallsDuringBluetoothMode": "Gestión de llamadas por Bluetooth",
  "indoor": "En interiores",
  "isCharging": "Se está cargando",
  "isChargingLeft": "Se está cargando (izquierda)",
  "isChargingRight": "Se está cargando (derecha)",
  "jazz": "Jazz",
  "latin": "Latina",
  "ldac": "LDAC",
  "left": "Izquierda",
  "leftDoublePress": "Doble pulsación en la izquierda",
  "leftLongPress": "Pulsación larga en la izquierda",
  "leftSinglePress": "Pulsación simple en la izquierda",
  "leftSlideDown": "Deslizar hacia la izquierda y hacia abajo",
  "leftSlideUp": "Deslizar hacia la izquierda hacia arriba",
  "leftTriplePress": "Triple pulsación en la izquierda",
  "lightOn": "Luz encendida",
  "lights": "Luces",
  "lightsBrightness": "Brillo de las luces de colores",
  "lightsColor": "Color de la luces de colores",
  "lightsEnabled": "Luces de colores activadas",
  "lightsMode": "Modo de las luces de colores",
  "limitHighVolume": "Limitar el volumen alto",
  "limitHighVolumeDbLimit": "Límite de decibelios",
  "limitHighVolumeRefreshRate": "Tasa de refresco de los decibelios",
  "listeningMode": "Modo de sonido ambiente",
  "listeningModePrompt": "Aviso de modo de escucha",
  "local": "Local",
  "lounge": "Lounge",
  "lowBatteryPrompt": "Aviso de batería baja",
  "lowNoise": "Bajo nivel de ruido",
  "manual": "Manual",
  "manualNoiseCanceling": "Cancelación manual del ruido",
  "manualTransparency": "Transparencia del manual",
  "manualUpdate": "Actualización manual",
  "medium": "Media",
  "mediumNoise": "Ruido moderado",
  "miscellaneous": "Misceláneo",
  "moderate": "Moderado",
  "monday": "Lunes",
  "movie": "Película",
  "movieMode": "Modo película",
  "multiScene": "Múltiples entornos",
  "multiSceneNoiseCanceling": "Cancelación de ruido en múltiples entornos",
  "music": "Música",
  "musicFollows": "La música te sigue",
  "nature": "Natural",
  "nextSong": "Siguiente canción",
  "no": "No",
  "noiseCanceling": "Cancelación de ruido",
  "noiseCancelingMode": "Modo cancelación de ruido",
  "noiseCancelingModeInCycle": "Modo de cancelación de ruido en ciclo",
  "noiseCancelingPrompt": "Indicación de cancelación de ruido",
  "none": "Ninguno",
  "normal": "Normal",
  "normalModeInCycle": "Modo normal en el ciclo",
  "notCharging": "No se carga",
  "original": "Original",
  "outdoor": "Al aire libre",
  "piano": "Piano",
  "plane": "Avión",
  "playPause": "Pausar la reproducción",
  "podcast": "Podcast",
  "pop": "Pop",
  "powerOff": "Apagado",
  "presetEqualizerProfile": "Perfil del preajuste",
  "presetProfile": "Perfil del preajuste",
  "pressureSensitivity": "Sensibilidad a la presión",
  "previousSong": "Canción anterior",
  "realTime": "En tiempo real",
  "realTimeAdaptiveNoiseCanceling": "Cancelación de ruido adaptativa en tiempo real",
  "remoteCamera": "Cámara remota",
  "resetButtonsToDefault": "Restablecer los botones a la configuración predeterminada",
  "rhythm": "Ritmo",
  "right": "Derecha",
  "rightDoublePress": "Pulsación doble a la derecha",
  "rightLongPress": "Pulsación prolongada a la derecha",
  "rightSinglePress": "Pulsación única a la derecha",
  "rightSlideDown": "Deslizar hacia la derecha",
  "rightSlideUp": "Deslizar hacia la derecha y hacia arriba",
  "rightTriplePress": "Triple pulsación a la derecha",
  "rnb": "RnB",
  "rock": "Rock",
  "saturday": "Sábado",
  "sendPacket": "Enviar el paquete de información",
  "serialNumber": "Número de serie",
  "sideTone": "Tono lateral",
  "singlePress": "Una sola pulsación",
  "smallSpeakers": "Altavoces pequeños",
  "softest": "Más suave",
  "soundLeakCompensation": "Compensación de fugas de sonido",
  "soundModes": "Modos de sonido",
  "spatialAudio": "Audio espacial",
  "spatialAudioMode": "Modo de audio espacial",
  "spatialAudioMusicMode": "Modo de música con audio espacial",
  "spokenWord": "Conversación",
  "stateUpdatePacket": "Paquete de información sobre el estado",
  "strong": "Fuerte",
  "sunday": "Domingo",
  "surroundSound": "Sonido envolvente",
  "talkMode": "Modo de conversación",
  "thursday": "Jueves",
  "touchLock": "Bloqueo táctil",
  "touchTone": "Marcación por tonos",
  "train": "Tren",
  "transparency": "Transparencia",
  "transparencyMode": "Modo transparencia",
  "transparencyModeInCycle": "Modo de transparencia en el ciclo",
  "transport": "Transporte",
  "transportation": "Transporte",
  "transportationMode": "Modo de transporte",
  "trebleBooster": "Potenciador de agudos",
  "trebleReducer": "Reductor de agudos",
  "tuesday": "Martes",
  "twsStatus": "Estado de los auriculares «True Wireless» (TWS)",
  "vocalMode": "Modo vocal",
  "voice": "Voz",
  "voiceAssistant": "Asistente de voz",
  "voicePrompt": "Mensaje de voz",
  "volume": "Volumen",
  "volumeAdjustments": "Ajustes del volumen",
  "volumeBalance": "Balance del volumen",
  "volumeBooster": "Potenciador de volumen",
  "volumeDown": "Bajar el volumen",
  "volumeUp": "Subir el volumen",
  "weak": "Débil",
  "wearingDetection": "Detección de uso",
  "wearingTone": "Tono al usarlo",
  "wednesday": "Miercoles",
  "windNoiseDetected": "Se ha detectado ruido del viento",
  "windNoiseSuppression": "Supresión del ruido del viento",
  "yes": "Sí"
 },
 "et": {
  "ambientSoundMode": "Ümbritseva heli režiim",
  "buttonConfiguration": "Nuppude seaded",
  "case": "Laadimisümbris",
  "deviceInformation": "Seadme teave",
  "dualConnections": "Kaksikühendus",
  "equalizer": "Ekvalaiser",
  "equalizerImportExport": "Ekvalaiseri import/eksport",
  "general": "Üldine",
  "lights": "Valgustus",
  "limitHighVolume": "Helitugevuse piirang",
  "listeningMode": "Kuulamisrežiim",
  "local": "Kohalik",
  "miscellaneous": "Muu",
  "noiseCanceling": "Mürasummutus",
  "normal": "Tavaline",
  "soundModes": "Helirežiimid",
  "transparency": "Läbipaistvus"
 },
 "fi": {
  "ambientSoundMode": "Ympäristöäänitila",
  "buttonConfiguration": "Painikeasetukset",
  "case": "Latauskotelo",
  "deviceInformation": "Laitteen tiedot",
  "dualConnections": "Kaksoisyhteys",
  "equalizer": "Taajuuskorjain",
  "equalizerImportExport": "Taajuuskorjaimen tuonti/vienti",
  "general": "Yleiset",
  "lights": "Valot",
  "limitHighVolume": "Äänenvoimakkuuden rajoitus",
  "listeningMode": "Kuuntelutila",
  "local": "Paikallinen",
  "miscellaneous": "Muut",
  "noiseCanceling": "Vastamelu",
  "normal": "Normaali",
  "soundModes": "Äänitilat",
  "transparency": "Läpikuuluvuus"
 },
 "fr": {
  "ambientSoundMode": "Mode son ambiant",
  "buttonConfiguration": "Configuration des boutons",
  "case": "Étui de charge",
  "deviceInformation": "Informations sur l’appareil",
  "disconnected": "Déconnecté",
  "dualConnections": "Double connexion",
  "equalizer": "Egaliseur",
  "equalizerImportExport": "Import/export de l’égaliseur",
  "general": "Général",
  "lights": "Éclairage",
  "limitHighVolume": "Limitation du volume",
  "listeningMode": "Mode d’écoute",
  "local": "Local",
  "miscellaneous": "Divers",
  "noiseCanceling": "Réduction de bruit",
  "none": "Aucun",
  "normal": "Normal",
  "soundModes": "Modes sonore",
  "transparency": "Transparence"
 },
 "gu": {
  "ambientSoundMode": "આસપાસના અવાજનો મોડ",
  "buttonConfiguration": "બટન ગોઠવણી",
  "case": "ચાર્જિંગ કેસ",
  "deviceInformation": "ઉપકરણ માહિતી",
  "dualConnections": "ડ્યુઅલ કનેક્શન",
  "equalizer": "ઇક્વલાઇઝર",
  "equalizerImportExport": "ઇક્વલાઇઝર આયાત/નિકાસ",
  "general": "સામાન્ય",
  "lights": "લાઇટ",
  "limitHighVolume": "અવાજ મર્યાદા",
  "listeningMode": "સાંભળવાનો મોડ",
  "local": "સ્થાનિક",
  "miscellaneous": "વિવિધ",
  "noiseCanceling": "નોઇઝ કેન્સલિંગ",
  "normal": "સામાન્ય",
  "soundModes": "સાઉન્ડ મોડ",
  "transparency": "ટ્રાન્સપરન્સી"
 },
 "hi": {
  "ambientSoundMode": "परिवेश ध्वनि मोड",
  "buttonConfiguration": "बटन कॉन्फ़िगरेशन",
  "case": "चार्जिंग केस",
  "deviceInformation": "डिवाइस जानकारी",
  "dualConnections": "ड्यूल कनेक्शन",
  "equalizer": "इक्वलाइज़र",
  "equalizerImportExport": "इक्वलाइज़र आयात/निर्यात",
  "general": "सामान्य",
  "lights": "लाइट",
  "limitHighVolume": "वॉल्यूम सीमा",
  "listeningMode": "सुनने का मोड",
  "local": "स्थानीय",
  "miscellaneous": "विविध",
  "noiseCanceling": "नॉइज़ कैंसलिंग",
  "normal": "सामान्य",
  "soundModes": "साउंड मोड",
  "transparency": "ट्रांसपेरेंसी"
 },
 "hu": {
  "ambientSoundMode": "Környezeti hang mód",
  "buttonConfiguration": "Gombok beállítása",
  "case": "Töltőtok",
  "deviceInformation": "Eszközinformáció",
  "dualConnections": "Kettős kapcsolat",
  "equalizer": "Hangszínszabályzó",
  "equalizerImportExport": "Hangszínszabályzó importálása/exportálása",
  "general": "Általános",
  "lights": "Világítás",
  "limitHighVolume": "Hangerőkorlát",
  "listeningMode": "Hallgatási mód",
  "local": "Helyi",
  "miscellaneous": "Egyéb",
  "noiseCanceling": "Zajszűrés",
  "normal": "Normál",
  "soundModes": "Hangzásmódok",
  "transparency": "Átlátszóság"
 },
 "it": {
  "acoustic": "Acustica",
  "adaptive": "Adattiva",
  "adaptiveNoiseCanceling": "Riduzione rumore adattiva",
  "adaptiveNoiseCancelingSensitivityLevel": "Livello di sensibilità della riduzione rumore adattiva",
  "airPressure": "Pressione atmosferica",
  "airplaneMode": "Modalità aereo",
  "ambientSoundMode": "Modalità Suono ambientale",
  "autoPowerOff": "Spegnimento automatico",
  "bassBooster": "Bassi amplificati",
  "bassReducer": "Bassi attenuati",
  "batteryLevel": "Livello batteria",
  "batteryLevelLeft": "Livello batteria (Sinistra)",
  "batteryLevelRight": "Livello batteria (Destra)",
  "bus": "Autobus",
  "buttonConfiguration": "Configurazione dei comandi",
  "buttonsEnabled": "Comandi abilitati",
  "car": "Macchina",
  "case": "Custodia di ricarica",
  "caseBatteryLevel": "Livello batteria della custodia",
  "charging": "In carica",
  "classical": "Classica",
  "connected": "Connesso",
  "custom": "Personalizzato",
  "customEqualizerProfile": "Profilo personalizzato",
  "customNoiseCanceling": "Riduzione rumore personalizzata",
  "customProfile": "Profilo personalizzato",
  "dance": "Dance",
  "deviceInformation": "Informazioni sul dispositivo",
  "disabled": "Disabilitato",
  "disconnected": "Disconnesso",
  "doublePress": "Tocco doppio",
  "dualConnections": "Connessione doppia",
  "dualConnectionsDevices": "Dispositivi per la connessione doppia",
  "electronic": "Elettronica",
  "equalizer": "Equalizzatore",
  "equalizerImportExport": "Importa/Esporta equalizzatore",
  "exportCustomEqualizerProfiles": "Esporta profili personalizzati",
  "exportCustomEqualizerProfilesOutput": "Esporta output dei profili personalizzati",
  "findDevice": "Trova dispositivo",
  "firmwareVersion": "Versione firmware",
  "firmwareVersionLeft": "Versione firmware (Sinistra)",
  "firmwareVersionRight": "Versione firmware (Destra)",
  "friday": "Venerdì",
  "gamingMode": "Modalità gioco",
  "general": "Generale",
  "highNoise": "Rumore alto",
  "hipHop": "Hip Hop",
  "importCustomEqualizerProfiles": "Importa profili personalizzati",
  "importCustomEqualizerProfilesConfirm": "Questa opzione sovrascriverà i profili esistenti che hanno lo stesso nome.",
  "indoor": "Al chiuso",
  "isCharging": "Stato di carica",
  "isChargingLeft": "Stato di carica (Sinistra)",
  "isChargingRight": "Stato di carica (Destra)",
  "jazz": "Jazz",
  "latin": "Latina",
  "left": "Sinistra",
  "leftDoublePress": "Tocco doppio (Sinistra)",
  "leftLongPress": "Tieni premuto (Sinistra)",
  "leftSinglePress": "Tocco singolo (Sinistra)",
  "leftTriplePress": "Tocco triplo (Sinistra)",
  "lights": "Luci",
  "limitHighVolume": "Limite volume",
  "listeningMode": "Modalità di ascolto",
  "local": "Locale",
  "lounge": "Lounge",
  "lowBatteryPrompt": "Avviso di batteria scarica",
  "lowNoise": "Rumore basso",
  "manual": "Manuale",
  "manualNoiseCanceling": "Riduzione rumore manuale",
  "manualTransparency": "Trasparenza manuale",
  "mediumNoise": "Rumore medio",
  "miscellaneous": "Varie",
  "moderate": "Moderato",
  "monday": "Lunedì",
  "multiScene": "Multi-scenario",
  "multiSceneNoiseCanceling": "Riduzione rumore multi-scenario",
  "nextSong": "Brano successivo",
  "no": "No",
  "noiseCanceling": "Riduzione rumore",
  "noiseCancelingMode": "Modalità Riduzione rumore",
  "none": "Non assegnato",
  "normal": "Normale",
  "notCharging": "Non in carica",
  "outdoor": "All'aperto",
  "piano": "Pianoforte",
  "plane": "Aereo",
  "playPause": "Riproduzione/Pausa",
  "podcast": "Podcast",
  "pop": "Pop",
  "presetEqualizerProfile": "Profilo preimpostato",
  "presetProfile": "Profilo preimpostato",
  "previousSong": "Brano precedente",
  "realTimeAdaptiveNoiseCanceling": "Riduzione rumore adattiva in tempo reale",
  "resetButtonsToDefault": "Reimposta i comandi predefiniti",
  "right": "Destra",
  "rightDoublePress": "Tocco doppio (Destra)",
  "rightLongPress": "Tieni premuto (Destra)",
  "rightSinglePress": "Tocco singolo (Destra)",
  "rightTriplePress": "Tocco triplo (Destra)",
  "rnb": "R&B",
  "rock": "Rock",
  "saturday": "Sabato",
  "sendPacket": "Invia pacchetto",
  "serialNumber": "Numero di serie",
  "singlePress": "Tocco singolo",
  "smallSpeakers": "Altoparlanti piccoli",
  "soundModes": "Modalità audio",
  "spokenWord": "Parlato",
  "stateUpdatePacket": "Pacchetto di aggiornamento dello stato",
  "strong": "Forte",
  "sunday": "Domenica",
  "surroundSound": "Suono surround",
  "thursday": "Giovedì",
  "touchTone": "Suono al tocco",
  "train": "Treno",
  "transparency": "Trasparenza",
  "transparencyMode": "Modalità Trasparenza",
  "transport": "Sui mezzi",
  "transportation": "Trasporto",
  "transportationMode": "Mezzo di trasporto",
  "trebleBooster": "Alti amplificati",
  "trebleReducer": "Alti attenuati",
  "tuesday": "Martedì",
  "twsStatus": "Stato True Wireless (TWS)",
  "voiceAssistant": "Assistente vocale",
  "volume": "Volume",
  "volumeAdjustments": "Regolazioni del volume",
  "volumeDown": "Abbassa il volume",
  "volumeUp": "Alza il volume",
  "weak": "Debole",
  "wednesday": "Mercoledì",
  "windNoiseDetected": "Rumore del vento rilevato",
  "windNoiseSuppression": "Riduzione rumore del vento",
  "yes": "Sì"
 },
 "kn": {
  "ambientSoundMode": "ಸುತ್ತಲಿನ ಧ್ವನಿ ಮೋಡ್",
  "buttonConfiguration": "ಬಟನ್ ಸಂರಚನೆ",
  "case": "ಚಾರ್ಜಿಂಗ್ ಕೇಸ್",
  "deviceInformation": "ಸಾಧನ ಮಾಹಿತಿ",
  "dualConnections": "ಡ್ಯುಯಲ್ ಸಂಪರ್ಕ",
  "equalizer": "ಈಕ್ವಲೈಜರ್",
  "equalizerImportExport": "ಈಕ್ವಲೈಜರ್ ಆಮದು/ರಫ್ತು",
  "general": "ಸಾಮಾನ್ಯ",
  "lights": "ದೀಪಗಳು",
  "limitHighVolume": "ವಾಲ್ಯೂಮ್ ಮಿತಿ",
  "listeningMode": "ಆಲಿಸುವ ಮೋಡ್",
  "local": "ಸ್ಥಳೀಯ",
  "miscellaneous": "ಇತರೆ",
  "noiseCanceling": "ಶಬ್ದ ರದ್ದತಿ",
  "normal": "ಸಾಮಾನ್ಯ",
  "soundModes": "ಧ್ವನಿ ಮೋಡ್‌ಗಳು",
  "transparency": "ಪಾರದರ್ಶಕತೆ"
 },
 "lt": {
  "ambientSoundMode": "Aplinkos garso režimas",
  "buttonConfiguration": "Mygtukų nustatymai",
  "case": "Įkrovimo dėklas",
  "deviceInformation": "Įrenginio informacija",
  "dualConnections": "Dvigubas ryšys",
  "equalizer": "Glodintuvas",
  "equalizerImportExport": "Glodintuvo importas/eksportas",
  "general": "Bendra",
  "lights": "Apšvietimas",
  "limitHighVolume": "Garsumo ribojimas",
  "listeningMode": "Klausymosi režimas",
  "local": "Vietinis",
  "miscellaneous": "Įvairūs",
  "noiseCanceling": "Triukšmo slopinimas",
  "normal": "Įprastas",
  "soundModes": "Garso režimai",
  "transparency": "Skaidrumas"
 },
 "lv": {
  "ambientSoundMode": "Apkārtējās skaņas režīms",
  "buttonConfiguration": "Pogu iestatījumi",
  "case": "Uzlādes futrālis",
  "deviceInformation": "Informācija par ierīci",
  "dualConnections": "Divkāršs savienojums",
  "equalizer": "Ekvalaizers",
  "equalizerImportExport": "Ekvalaizera imports/eksports",
  "general": "Vispārīgi",
  "lights": "Apgaismojums",
  "limitHighVolume": "Skaļuma ierobežojums",
  "listeningMode": "Klausīšanās režīms",
  "local": "Lokāli",
  "miscellaneous": "Dažādi",
  "noiseCanceling": "Trokšņu slāpēšana",
  "normal": "Parasts",
  "soundModes": "Skaņas režīmi",
  "transparency": "Caurspīdīgums"
 },
 "ml": {
  "ambientSoundMode": "ചുറ്റുപാടിലെ ശബ്ദ മോഡ്",
  "buttonConfiguration": "ബട്ടൺ ക്രമീകരണം",
  "case": "ചാർജിംഗ് കേസ്",
  "deviceInformation": "ഉപകരണ വിവരങ്ങൾ",
  "dualConnections": "ഡ്യുവൽ കണക്ഷൻ",
  "equalizer": "ഇക്വലൈസർ",
  "equalizerImportExport": "ഇക്വലൈസർ ഇമ്പോർട്ട്/എക്‌സ്‌പോർട്ട്",
  "general": "പൊതുവായത്",
  "lights": "ലൈറ്റുകൾ",
  "limitHighVolume": "വോളിയം പരിധി",
  "listeningMode": "കേൾക്കൽ മോഡ്",
  "local": "പ്രാദേശികം",
  "miscellaneous": "മറ്റുള്ളവ",
  "noiseCanceling": "നോയ്സ് ക്യാൻസലിംഗ്",
  "normal": "സാധാരണ",
  "soundModes": "ശബ്ദ മോഡുകൾ",
  "transparency": "ട്രാൻസ്പരൻസി"
 },
 "mr": {
  "ambientSoundMode": "सभोवतालचा ध्वनी मोड",
  "buttonConfiguration": "बटण कॉन्फिगरेशन",
  "case": "चार्जिंग केस",
  "deviceInformation": "डिव्हाइस माहिती",
  "dualConnections": "दुहेरी कनेक्शन",
  "equalizer": "इक्वलायझर",
  "equalizerImportExport": "इक्वलायझर आयात/निर्यात",
  "general": "सामान्य",
  "lights": "प्रकाश",
  "limitHighVolume": "आवाज मर्यादा",
  "listeningMode": "ऐकण्याचा मोड",
  "local": "स्थानिक",
  "miscellaneous": "इतर",
  "noiseCanceling": "नॉइज कॅन्सलिंग",
  "normal": "सामान्य",
  "soundModes": "ध्वनी मोड",
  "transparency": "ट्रान्सपरन्सी"
 },
 "nb": {
  "ambientSoundMode": "Omgivelseslydmodus",
  "buttonConfiguration": "Knappeoppsett",
  "case": "Ladeetui",
  "deviceInformation": "Enhetsinformasjon",
  "dualConnections": "Dobbel tilkobling",
  "equalizer": "Equalizer",
  "equalizerImportExport": "Equalizer-import/-eksport",
  "general": "Generelt",
  "lights": "Lys",
  "limitHighVolume": "Volumbegrensning",
  "listeningMode": "Lyttemodus",
  "local": "Lokal",
  "miscellaneous": "Diverse",
  "noiseCanceling": "Støydemping",
  "normal": "Normal",
  "soundModes": "Lydmoduser",
  "transparency": "Gjennomhørbarhet"
 },
 "nl": {
  "ambientSoundMode": "Omgevingsgeluidmodus",
  "buttonConfiguration": "Knopinstellingen",
  "case": "Oplaadhoesje",
  "deviceInformation": "Apparaatinformatie",
  "dualConnections": "Dubbele verbinding",
  "equalizer": "Equalizer",
  "equalizerImportExport": "Equalizer importeren/exporteren",
  "general": "Algemeen",
  "lights": "Verlichting",
  "limitHighVolume": "Volumebegrenzing",
  "listeningMode": "Luistermodus",
  "local": "Lokaal",
  "miscellaneous": "Overig",
  "noiseCanceling": "Ruisonderdrukking",
  "normal": "Normaal",
  "soundModes": "Geluidsmodi",
  "transparency": "Transparantie"
 },
 "pa": {
  "ambientSoundMode": "ਆਲੇ-ਦੁਆਲੇ ਦੀ ਆਵਾਜ਼ ਮੋਡ",
  "buttonConfiguration": "ਬਟਨ ਸੰਰਚਨਾ",
  "case": "ਚਾਰਜਿੰਗ ਕੇਸ",
  "deviceInformation": "ਡਿਵਾਈਸ ਜਾਣਕਾਰੀ",
  "dualConnections": "ਦੋਹਰਾ ਕਨੈਕਸ਼ਨ",
  "equalizer": "ਇਕੁਅਲਾਈਜ਼ਰ",
  "equalizerImportExport": "ਇਕੁਅਲਾਈਜ਼ਰ ਆਯਾਤ/ਨਿਰਯਾਤ",
  "general": "ਆਮ",
  "lights": "ਲਾਈਟਾਂ",
  "limitHighVolume": "ਆਵਾਜ਼ ਸੀਮਾ",
  "listeningMode": "ਸੁਣਨ ਦਾ ਮੋਡ",
  "local": "ਸਥਾਨਕ",
  "miscellaneous": "ਫੁਟਕਲ",
  "noiseCanceling": "ਸ਼ੋਰ ਰੱਦ ਕਰਨਾ",
  "normal": "ਆਮ",
  "soundModes": "ਸਾਊਂਡ ਮੋਡ",
  "transparency": "ਪਾਰਦਰਸ਼ਤਾ"
 },
 "pl": {
  "ambientSoundMode": "Tryb dźwięków otoczenia",
  "buttonConfiguration": "Konfiguracja przycisków",
  "case": "Etui ładujące",
  "deviceInformation": "Informacje o urządzeniu",
  "disconnected": "Rozłączono",
  "dualConnections": "Podwójne połączenie",
  "equalizer": "Korektor",
  "equalizerImportExport": "Import/eksport korektora",
  "general": "Ogólne",
  "lights": "Oświetlenie",
  "limitHighVolume": "Ograniczenie głośności",
  "listeningMode": "Tryb słuchania",
  "local": "Lokalny",
  "miscellaneous": "Różne",
  "noiseCanceling": "Redukcja szumów",
  "normal": "Normalny",
  "soundModes": "Tryby dźwięku",
  "transparency": "Przezroczystość"
 },
 "pt": {
  "acoustic": "Acústico",
  "adaptive": "Adaptativo",
  "adaptiveNoiseCanceling": "Cancelamento de Ruído Adaptativo",
  "adaptiveNoiseCancelingSensitivityLevel": "Nível de sensibilidade do Cancelamento de Ruído Adaptativo",
  "airPressure": "Pressão Atmosférica",
  "airplaneMode": "Modo Avião",
  "alarms": "Alarmes",
  "ambientSoundMode": "Modo de som ambiente",
  "ancPersonalizedToEarCanal": "Cancelamento de Ruído Personalizado ao Canal Auricular",
  "atmospheric": "Atmosférico",
  "autoLightsOffMinutes": "Desligamento Automático das Luzes (minutos)",
  "autoPlayPause": "Reprodução/Pausa automáticas",
  "autoPowerOff": "Desligamento Automático",
  "autoPowerOffPrompt": "Aviso de Desligar Automático",
  "autoStopTimer": "Temporizador de Parada Automática",
  "autoStopTimerDuration": "Duração do Temporizador de Parada Automática",
  "automaticUpdate": "Atualização Automática",
  "balanced": "Equilibrado",
  "bassBooster": "Amplificador de Graves",
  "bassOff": "Sem Graves",
  "bassReducer": "Redutor de Graves",
  "bassUp": "Mais Grave",
  "batteryLevel": "Nível da Bateria",
  "batteryLevelLeft": "Nível da bateria (esquerda)",
  "batteryLevelRight": "Nível da bateria (direita)",
  "bloom": "Florescer",
  "bluetooth": "Bluetooth",
  "breathing": "Respiração",
  "bus": "Ônibus",
  "buttonConfiguration": "Configuração dos botões",
  "buttonsEnabled": "Botões Ativados",
  "car": "Carro",
  "case": "Estojo de carregamento",
  "caseBatteryLevel": "Bateria da caixa",
  "caseFirmwareVersion": "Versão de Firmware da Caixa",
  "caseLanguage": "Idioma da Caixa",
  "caseSerialNumber": "Numero de Série da Caixa",
  "changeMode": "Alterar Modo",
  "charging": "Carregando",
  "classic": "Clássica",
  "classical": "Clássico",
  "connected": "Conectado",
  "custom": "Personalizado",
  "customEqualizerProfile": "Perfil Personalizado",
  "customNoiseCanceling": "Cancelamento de Ruído Personalizado",
  "customProfile": "Perfil Personalizado",
  "dance": "Dança",
  "dbLimit": "Limite de Decibéis",
  "dbRefreshRate": "Taxa de Atualização de dB",
  "deep": "Deep",
  "defaultListeningMode": "Modo de Escuta Prédefinido",
  "deviceInformation": "Informações do dispositivo",
  "disabled": "Desativado",
  "disconnected": "Desconectado",
  "dolbyAudio": "Dolby Audio",
  "doublePress": "Toque duplo",
  "dualConnections": "Ligação dupla",
  "dualConnectionsDevices": "Dispositivos de conexão dupla",
  "easyChat": "Easy Chat",
  "easyChatWaitTime": "Tempo de espera Easy Chat",
  "electronic": "Eletrônica",
  "enabled": "Ativado",
  "environmentDetection": "Detecção de Ambiente",
  "equalizer": "Equalizador",
  "equalizerImportExport": "Importar/exportar equalizador",
  "exportCustomEqualizerProfiles": "Exportar Perfis Personalizados",
  "exportCustomEqualizerProfilesOutput": "Exportar Perfis Personalizados gerados",
  "findDevice": "Encontrar dispositivo",
  "firmest": "Firme",
  "firmwareVersion": "Versão do Firmware",
  "firmwareVersionLeft": "Versão do Firmware (esquerda)",
  "firmwareVersionRight": "Versão do Firmware (direita)",
  "fixed": "Fixo",
  "flash": "Flash",
  "flat": "Flat",
  "friday": "Sexta-feira",
  "fullyTransparent": "Totalmente Transparente",
  "gaming": "Jogo",
  "gamingMode": "Modo Jogo",
  "general": "Geral",
  "glow": "Brilho",
  "headTracking": "Detecção de cabeça",
  "heavy": "Heavy",
  "highNoise": "Ruído Alto",
  "hipHop": "Hip-Hop",
  "hostDevice": "Dispositivo Host",
  "immersiveExperience": "Experiência imersiva",
  "importCustomEqualizerProfiles": "Importar Perfis Personalizados",
  "importCustomEqualizerProfilesConfirm": "Isto substituirá perfis existentes que tenham o mesmo nome.",
  "incomingCallsDuringBluetoothMode": "Receber Chamadas durante Modo Bluetooth",
  "indoor": "Interior",
  "isCharging": "Está carregando",
  "isChargingLeft": "Está carregando (esquerda)",
  "isChargingRight": "Está carregando (direita)",
  "jazz": "Jazz",
  "latin": "Latina",
  "ldac": "LDAC",
  "left": "Esquerda",
  "leftDoublePress": "Toque duplo na esquerda",
  "leftLongPress": "Toque longo na esquerda",
  "leftSinglePress": "Toque simples na esquerda",
  "leftSlideDown": "Deslizar para baixo na esquerda",
  "leftSlideUp": "Deslizar para cima na esquerda",
  "leftTriplePress": "Toque triplo na esquerda",
  "lightOn": "Luz acesa",
  "lights": "Luzes",
  "lightsBrightness": "Brilho das Luzes Coloridas",
  "lightsColor": "Cor das Luzes Coloridas",
  "lightsEnabled": "Luzes Coloridas Ativadas",
  "lightsMode": "Modo de Luzes Coloridas",
  "limitHighVolume": "Limite de volume",
  "limitHighVolumeDbLimit": "Limite de Decibéis",
  "limitHighVolumeRefreshRate": "Taxa de Atualização de dB",
  "listeningMode": "Modo de audição",
  "listeningModePrompt": "Aviso de Modo de Escuta",
  "local": "Local",
  "lounge": "Lounge",
  "lowBatteryPrompt": "Aviso de bateria baixa",
  "lowNoise": "Ruído baixo",
  "manual": "Manual",
  "manualNoiseCanceling": "Cancelamento de Ruído Manual",
  "manualTransparency": "Transparência Manual",
  "manualUpdate": "Atualização Manual",
  "medium": "Média",
  "mediumNoise": "Ruído moderado",
  "miscellaneous": "Diversos",
  "moderate": "Moderado",
  "monday": "Segunda-feira",
  "movie": "Filme",
  "movieMode": "Modo Filme",
  "multiScene": "Múltiplos Ambientes",
  "multiSceneNoiseCanceling": "Cancelamento de Ruído em Múltiplos Ambientes",
  "music": "Música",
  "musicFollows": "Acompanha a música",
  "nature": "Natureza",
  "nextSong": "Próxima Faixa",
  "no": "Não",
  "noiseCanceling": "Cancelamento de ruído",
  "noiseCancelingMode": "Modo Cancelamento de Ruído",
  "noiseCancelingModeInCycle": "Modo Cancelamento de Ruido em ciclo",
  "noiseCancelingPrompt": "Indicação de Cancelamento de Ruído",
  "none": "Nenhum",
  "normal": "Normal",
  "normalModeInCycle": "Modo Normal em ciclo",
  "notCharging": "Sem carregar",
  "original": "Original",
  "outdoor": "Ar Livre",
  "piano": "Piano",
  "plane": "Avião",
  "playPause": "Pausar",
  "podcast": "Podcast",
  "pop": "Pop",
  "powerOff": "Desligado",
  "presetEqualizerProfile": "Prefil de Predefinição",
  "presetProfile": "Prefil de Predefinição",
  "pressureSensitivity": "Sensibilidade à pressão",
  "previousSong": "Faixa Anterior",
  "realTime": "Tempo Real",
  "realTimeAdaptiveNoiseCanceling": "Cancelamento de Ruído Adaptativo em Tempo Real",
  "remoteCamera": "Câmera remota",
  "resetButtonsToDefault": "Redefinir a configuração de botões",
  "rhythm": "Ritmo",
  "right": "Direita",
  "rightDoublePress": "Toque duplo na direita",
  "rightLongPress": "Toque longo na direita",
  "rightSinglePress": "Toque simples na direita",
  "rightSlideDown": "Deslizar para baixo na direita",
  "rightSlideUp": "Deslizar para cima na direita",
  "rightTriplePress": "Toque triplo na direita",
  "rnb": "R&B",
  "rock": "Rock",
  "saturday": "Sábado",
  "sendPacket": "Enviar pacote de informação",
  "serialNumber": "Número de Série",
  "sideTone": "Tom lateral",
  "singlePress": "Toque simples",
  "smallSpeakers": "Pequenos Alto-Falantes",
  "softest": "Mais suave",
  "soundLeakCompensation": "Compensação de Vazamento de Som",
  "soundModes": "Modos de som",
  "spatialAudio": "Audio Espacial",
  "spatialAudioMode": "Modo de Áudio Espacial",
  "spatialAudioMusicMode": "Música com Áudio Espacial",
  "spokenWord": "Palavra",
  "stateUpdatePacket": "Pacote de Atualização de Estado",
  "strong": "Forte",
  "sunday": "Domingo",
  "surroundSound": "Som Surround",
  "talkMode": "Modo Conversação",
  "thursday": "Quinta-feira",
  "touchLock": "Bloqueio de toque",
  "touchTone": "Tons de toque",
  "train": "Trêm",
  "transparency": "Transparência",
  "transparencyMode": "Modo Transparência",
  "transparencyModeInCycle": "Modo Transparência em ciclo",
  "transport": "Transporte",
  "transportation": "Transporte",
  "transportationMode": "Modo Transporte",
  "trebleBooster": "Amplificador de Agudos",
  "trebleReducer": "Redutor de Agudos",
  "tuesday": "Terça-feira",
  "twsStatus": "Status do Wireless (TWS)",
  "vocalMode": "Modo de Voz",
  "voice": "Voz",
  "voiceAssistant": "Assistente de Voz",
  "voicePrompt": "Mensagem de Voz",
  "volume": "Volume",
  "volumeAdjustments": "Ajustes de Volume",
  "volumeBalance": "Balanço de Volume",
  "volumeBooster": "Aumento de Volume",
  "volumeDown": "Diminuir Volume",
  "volumeUp": "Aumentar Volume",
  "weak": "Fraco",
  "wearingDetection": "Detecção de uso",
  "wearingTone": "Tom de uso",
  "wednesday": "Quarta-feira",
  "windNoiseDetected": "Ruído de Vento Detectado",
  "windNoiseSuppression": "Supressão de Ruído de Vento",
  "yes": "Sim"
 },
 "pt_BR": {
  "acoustic": "Acústico",
  "adaptive": "Adaptativo",
  "adaptiveNoiseCanceling": "Cancelamento de Ruído Adaptativo",
  "adaptiveNoiseCancelingSensitivityLevel": "Nível de sensibilidade do Cancelamento de Ruído Adaptativo",
  "airPressure": "Pressão Atmosférica",
  "airplaneMode": "Modo Avião",
  "alarms": "Alarmes",
  "ambientSoundMode": "Modo Som Ambiente",
  "ancPersonalizedToEarCanal": "Cancelamento de Ruído Personalizado ao Canal Auricular",
  "atmospheric": "Atmosférico",
  "autoLightsOffMinutes": "Desligamento Automático das Luzes (minutos)",
  "autoPlayPause": "Reprodução/Pausa automáticas",
  "autoPowerOff": "Desligamento Automático",
  "autoPowerOffPrompt": "Aviso de Desligar Automático",
  "autoStopTimer": "Temporizador de Parada Automática",
  "autoStopTimerDuration": "Duração do Temporizador de Parada Automática",
  "automaticUpdate": "Atualização Automática",
  "balanced": "Equilibrado",
  "bassBooster": "Amplificador de Graves",
  "bassOff": "Sem Graves",
  "bassReducer": "Redutor de Graves",
  "bassUp": "Mais Grave",
  "batteryLevel": "Nível da Bateria",
  "batteryLevelLeft": "Nível da bateria (esquerda)",
  "batteryLevelRight": "Nível da bateria (direita)",
  "bloom": "Florescer",
  "bluetooth": "Bluetooth",
  "breathing": "Respiração",
  "bus": "Ônibus",
  "buttonConfiguration": "Configuração de Botões",
  "buttonsEnabled": "Botões Ativados",
  "car": "Carro",
  "case": "Caixa",
  "caseBatteryLevel": "Bateria da caixa",
  "caseFirmwareVersion": "Versão de Firmware da Caixa",
  "caseLanguage": "Idioma da Caixa",
  "caseSerialNumber": "Numero de Série da Caixa",
  "changeMode": "Alterar Modo",
  "charging": "Carregando",
  "classic": "Clássica",
  "classical": "Clássico",
  "connected": "Conectado",
  "custom": "Personalizado",
  "customEqualizerProfile": "Perfil Personalizado",
  "customNoiseCanceling": "Cancelamento de Ruído Personalizado",
  "customProfile": "Perfil Personalizado",
  "dance": "Dança",
  "dbLimit": "Limite de Decibéis",
  "dbRefreshRate": "Taxa de Atualização de dB",
  "deep": "Deep",
  "defaultListeningMode": "Modo de Escuta Prédefinido",
  "deviceInformation": "Informações do Dispositivo",
  "disabled": "Desativado",
  "disconnected": "Desconectado",
  "dolbyAudio": "Dolby Audio",
  "doublePress": "Toque duplo",
  "dualConnections": "Conexão dupla",
  "dualConnectionsDevices": "Dispositivos de conexão dupla",
  "easyChat": "Easy Chat",
  "easyChatWaitTime": "Tempo de espera Easy Chat",
  "electronic": "Eletrônica",
  "enabled": "Ativado",
  "environmentDetection": "Detecção de Ambiente",
  "equalizer": "Equalizador",
  "equalizerImportExport": "Importar/Exportar Equalizador",
  "exportCustomEqualizerProfiles": "Exportar Perfis Personalizados",
  "exportCustomEqualizerProfilesOutput": "Exportar Perfis Personalizados gerados",
  "findDevice": "Encontrar dispositivo",
  "firmest": "Firme",
  "firmwareVersion": "Versão do Firmware",
  "firmwareVersionLeft": "Versão do Firmware (esquerda)",
  "firmwareVersionRight": "Versão do Firmware (direita)",
  "fixed": "Fixo",
  "flash": "Flash",
  "flat": "Flat",
  "friday": "Sexta-feira",
  "fullyTransparent": "Totalmente Transparente",
  "gaming": "Jogo",
  "gamingMode": "Modo Jogo",
  "general": "Geral",
  "glow": "Brilho",
  "headTracking": "Detecção de cabeça",
  "heavy": "Heavy",
  "highNoise": "Ruído Alto",
  "hipHop": "Hip-Hop",
  "hostDevice": "Dispositivo Host",
  "immersiveExperience": "Experiência imersiva",
  "importCustomEqualizerProfiles": "Importar Perfis Personalizados",
  "importCustomEqualizerProfilesConfirm": "Isto substituirá perfis existentes que tenham o mesmo nome.",
  "incomingCallsDuringBluetoothMode": "Receber Chamadas durante Modo Bluetooth",
  "indoor": "Interior",
  "isCharging": "Está carregando",
  "isChargingLeft": "Está carregando (esquerda)",
  "isChargingRight": "Está carregando (direita)",
  "jazz": "Jazz",
  "latin": "Latina",
  "ldac": "LDAC",
  "left": "Esquerda",
  "leftDoublePress": "Toque duplo na esquerda",
  "leftLongPress": "Toque longo na esquerda",
  "leftSinglePress": "Toque simples na esquerda",
  "leftSlideDown": "Deslizar para baixo na esquerda",
  "leftSlideUp": "Deslizar para cima na esquerda",
  "leftTriplePress": "Toque triplo na esquerda",
  "lightOn": "Luz acesa",
  "lights": "Luzes",
  "lightsBrightness": "Brilho das Luzes Coloridas",
  "lightsColor": "Cor das Luzes Coloridas",
  "lightsEnabled": "Luzes Coloridas Ativadas",
  "lightsMode": "Modo de Luzes Coloridas",
  "limitHighVolume": "Limitar volume máximo",
  "limitHighVolumeDbLimit": "Limite de Decibéis",
  "limitHighVolumeRefreshRate": "Taxa de Atualização de dB",
  "listeningMode": "Modo de Escuta",
  "listeningModePrompt": "Aviso de Modo de Escuta",
  "local": "Local",
  "lounge": "Lounge",
  "lowBatteryPrompt": "Aviso de bateria baixa",
  "lowNoise": "Ruído baixo",
  "manual": "Manual",
  "manualNoiseCanceling": "Cancelamento de Ruído Manual",
  "manualTransparency": "Transparência Manual",
  "manualUpdate": "Atualização Manual",
  "medium": "Média",
  "mediumNoise": "Ruído moderado",
  "miscellaneous": "Miscelânea",
  "moderate": "Moderado",
  "monday": "Segunda-feira",
  "movie": "Filme",
  "movieMode": "Modo Filme",
  "multiScene": "Múltiplos Ambientes",
  "multiSceneNoiseCanceling": "Cancelamento de Ruído em Múltiplos Ambientes",
  "music": "Música",
  "musicFollows": "Acompanha a música",
  "nature": "Natureza",
  "nextSong": "Próxima Faixa",
  "no": "Não",
  "noiseCanceling": "Cancelamento de Ruído",
  "noiseCancelingMode": "Modo Cancelamento de Ruído",
  "noiseCancelingModeInCycle": "Modo Cancelamento de Ruido em ciclo",
  "noiseCancelingPrompt": "Indicação de Cancelamento de Ruído",
  "none": "Nenhum",
  "normal": "Normal",
  "normalModeInCycle": "Modo Normal em ciclo",
  "notCharging": "Sem carregar",
  "original": "Original",
  "outdoor": "Ar Livre",
  "piano": "Piano",
  "plane": "Avião",
  "playPause": "Pausar",
  "podcast": "Podcast",
  "pop": "Pop",
  "powerOff": "Desligado",
  "presetEqualizerProfile": "Prefil de Predefinição",
  "presetProfile": "Prefil de Predefinição",
  "pressureSensitivity": "Sensibilidade à pressão",
  "previousSong": "Faixa Anterior",
  "realTime": "Tempo Real",
  "realTimeAdaptiveNoiseCanceling": "Cancelamento de Ruído Adaptativo em Tempo Real",
  "remoteCamera": "Câmera remota",
  "resetButtonsToDefault": "Redefinir a configuração de botões",
  "rhythm": "Ritmo",
  "right": "Direita",
  "rightDoublePress": "Toque duplo na direita",
  "rightLongPress": "Toque longo na direita",
  "rightSinglePress": "Toque simples na direita",
  "rightSlideDown": "Deslizar para baixo na direita",
  "rightSlideUp": "Deslizar para cima na direita",
  "rightTriplePress": "Toque triplo na direita",
  "rnb": "R&B",
  "rock": "Rock",
  "saturday": "Sábado",
  "sendPacket": "Enviar pacote de informação",
  "serialNumber": "Número de Série",
  "sideTone": "Tom lateral",
  "singlePress": "Toque simples",
  "smallSpeakers": "Pequenos Alto-Falantes",
  "softest": "Mais suave",
  "soundLeakCompensation": "Compensação de Vazamento de Som",
  "soundModes": "Modo de Som",
  "spatialAudio": "Audio Espacial",
  "spatialAudioMode": "Modo de Áudio Espacial",
  "spatialAudioMusicMode": "Música com Áudio Espacial",
  "spokenWord": "Palavra",
  "stateUpdatePacket": "Pacote de Atualização de Estado",
  "strong": "Forte",
  "sunday": "Domingo",
  "surroundSound": "Som Surround",
  "talkMode": "Modo Conversação",
  "thursday": "Quinta-feira",
  "touchLock": "Bloqueio de toque",
  "touchTone": "Tons de toque",
  "train": "Trêm",
  "transparency": "Transparência",
  "transparencyMode": "Modo Transparência",
  "transparencyModeInCycle": "Modo Transparência em ciclo",
  "transport": "Transporte",
  "transportation": "Transporte",
  "transportationMode": "Modo Transporte",
  "trebleBooster": "Amplificador de Agudos",
  "trebleReducer": "Redutor de Agudos",
  "tuesday": "Terça-feira",
  "twsStatus": "Status do Wireless (TWS)",
  "vocalMode": "Modo de Voz",
  "voice": "Voz",
  "voiceAssistant": "Assistente de Voz",
  "voicePrompt": "Mensagem de Voz",
  "volume": "Volume",
  "volumeAdjustments": "Ajustes de Volume",
  "volumeBalance": "Balanço de Volume",
  "volumeBooster": "Aumento de Volume",
  "volumeDown": "Diminuir Volume",
  "volumeUp": "Aumentar Volume",
  "weak": "Fraco",
  "wearingDetection": "Detecção de uso",
  "wearingTone": "Tom de uso",
  "wednesday": "Quarta-feira",
  "windNoiseDetected": "Ruído de Vento Detectado",
  "windNoiseSuppression": "Supressão de Ruído de Vento",
  "yes": "Sim"
 },
 "ro": {
  "ambientSoundMode": "Mod sunet ambiental",
  "buttonConfiguration": "Configurarea butoanelor",
  "case": "Carcasă de încărcare",
  "deviceInformation": "Informații despre dispozitiv",
  "dualConnections": "Conexiune dublă",
  "equalizer": "Egalizator",
  "equalizerImportExport": "Import/export egalizator",
  "general": "General",
  "lights": "Lumini",
  "limitHighVolume": "Limitarea volumului",
  "listeningMode": "Mod de ascultare",
  "local": "Local",
  "miscellaneous": "Diverse",
  "noiseCanceling": "Anularea zgomotului",
  "normal": "Normal",
  "soundModes": "Moduri de sunet",
  "transparency": "Transparență"
 },
 "ru": {
  "adaptive": "Адаптивный",
  "adaptiveNoiseCanceling": "Адаптивное шумоподавление",
  "adaptiveNoiseCancelingSensitivityLevel": "Уровень чувствительности адаптивного шумоподавления",
  "ambientSoundMode": "Режим окружающего звука",
  "ancPersonalizedToEarCanal": "Индивидуальная настройка шумоподавления для ушного канала",
  "bus": "Автобус",
  "buttonConfiguration": "Настройка кнопок",
  "car": "Машина",
  "case": "Зарядный кейс",
  "connected": "Подключено",
  "custom": "Cобственный",
  "customEqualizerProfile": "Пользовательский профиль",
  "customNoiseCanceling": "Пользовательское шумоподавление",
  "customProfile": "Пользовательский профиль",
  "deviceInformation": "Информация об устройстве",
  "disconnected": "Отключено",
  "dualConnections": "Двойное подключение",
  "environmentDetection": "Определение среды",
  "equalizer": "Эквалайзер",
  "equalizerImportExport": "Импорт/экспорт эквалайзера",
  "exportCustomEqualizerProfiles": "Экспорт пользовательских профилей",
  "exportCustomEqualizerProfilesOutput": "Результаты экспорта пользовательских профилей",
  "fullyTransparent": "Полная прозрачность",
  "general": "Общее",
  "highNoise": "Высокий шум",
  "importCustomEqualizerProfiles": "Импорт пользовательских профилей",
  "importCustomEqualizerProfilesConfirm": "Это перезапишет существующие профили с одинаковыми именами.",
  "indoor": "В помещении",
  "lights": "Подсветка",
  "limitHighVolume": "Ограничение громкости",
  "listeningMode": "Режим прослушивания",
  "local": "Локально",
  "lowNoise": "Низкий шум",
  "manual": "Ручной",
  "manualNoiseCanceling": "Ручное шумоподавление",
  "manualTransparency": "Ручная прозрачность",
  "mediumNoise": "Средний шум",
  "miscellaneous": "Прочее",
  "moderate": "Умеренный",
  "multiScene": "Мультисцена",
  "multiSceneNoiseCanceling": "Мультисценовое шумоподавление",
  "noiseCanceling": "Шумоподавление",
  "noiseCancelingMode": "Режим шумоподавления",
  "none": "Нет",
  "normal": "Обычный",
  "outdoor": "Снаружи",
  "plane": "Самолёт",
  "presetEqualizerProfile": "Профиль по умолчанию",
  "presetProfile": "Профиль по умолчанию",
  "soundModes": "Звуковые режимы",
  "strong": "Сильный",
  "talkMode": "Режим разговора",
  "train": "Поезд",
  "transparency": "Прозрачность",
  "transparencyMode": "Режим прозрачности",
  "transport": "Транспорт",
  "transportation": "Транспортировка",
  "transportationMode": "Режим транспортировки",
  "vocalMode": "Голосовой режим",
  "volume": "Громкость",
  "volumeAdjustments": "Настройки громкости",
  "weak": "Слабый",
  "windNoiseDetected": "Обнаружен шум ветра",
  "windNoiseSuppression": "Подавление шума ветра"
 },
 "sk": {
  "ambientSoundMode": "Režim okolitého zvuku",
  "buttonConfiguration": "Nastavenie tlačidiel",
  "case": "Nabíjacie puzdro",
  "deviceInformation": "Informácie o zariadení",
  "dualConnections": "Dvojité pripojenie",
  "equalizer": "Ekvalizér",
  "equalizerImportExport": "Import/export ekvalizéra",
  "general": "Všeobecné",
  "lights": "Osvetlenie",
  "limitHighVolume": "Obmedzenie hlasitosti",
  "listeningMode": "Režim počúvania",
  "local": "Miestne",
  "miscellaneous": "Rôzne",
  "noiseCanceling": "Potlačenie hluku",
  "normal": "Normálny",
  "soundModes": "Zvukové režimy",
  "transparency": "Priepustnosť"
 },
 "sl": {
  "ambientSoundMode": "Način zvokov okolice",
  "buttonConfiguration": "Nastavitev gumbov",
  "case": "Polnilni etui",
  "deviceInformation": "Podatki o napravi",
  "dualConnections": "Dvojna povezava",
  "equalizer": "Izenačevalnik",
  "equalizerImportExport": "Uvoz/izvoz izenačevalnika",
  "general": "Splošno",
  "lights": "Osvetlitev",
  "limitHighVolume": "Omejitev glasnosti",
  "listeningMode": "Način poslušanja",
  "local": "Lokalno",
  "miscellaneous": "Razno",
  "noiseCanceling": "Odpravljanje šumov",
  "normal": "Običajno",
  "soundModes": "Zvočni načini",
  "transparency": "Prepustnost"
 },
 "sv": {
  "ambientSoundMode": "Omgivningsljudläge",
  "buttonConfiguration": "Knappinställningar",
  "case": "Laddningsfodral",
  "deviceInformation": "Enhetsinformation",
  "dualConnections": "Dubbel anslutning",
  "equalizer": "Equalizer",
  "equalizerImportExport": "Import/export av equalizer",
  "general": "Allmänt",
  "lights": "Belysning",
  "limitHighVolume": "Volymbegränsning",
  "listeningMode": "Lyssningsläge",
  "local": "Lokalt",
  "miscellaneous": "Övrigt",
  "noiseCanceling": "Brusreducering",
  "normal": "Normal",
  "soundModes": "Ljudlägen",
  "transparency": "Transparens"
 },
 "ta": {
  "ambientSoundMode": "சூழல் ஒலி பயன்முறை",
  "buttonConfiguration": "பொத்தான் அமைப்பு",
  "case": "சார்ஜிங் பெட்டி",
  "deviceInformation": "சாதனத் தகவல்",
  "dualConnections": "இரட்டை இணைப்பு",
  "equalizer": "ஈக்வலைசர்",
  "equalizerImportExport": "ஈக்வலைசர் இறக்குமதி/ஏற்றுமதி",
  "general": "பொது",
  "lights": "விளக்குகள்",
  "limitHighVolume": "ஒலியளவு வரம்பு",
  "listeningMode": "கேட்கும் பயன்முறை",
  "local": "உள்ளூர்",
  "miscellaneous": "இதர",
  "noiseCanceling": "இரைச்சல் நீக்கம்",
  "normal": "இயல்பு",
  "soundModes": "ஒலி பயன்முறைகள்",
  "transparency": "வெளிப்படைத்தன்மை"
 },
 "te": {
  "ambientSoundMode": "పరిసర శబ్ద మోడ్",
  "buttonConfiguration": "బటన్ కాన్ఫిగరేషన్",
  "case": "ఛార్జింగ్ కేస్",
  "deviceInformation": "పరికర సమాచారం",
  "dualConnections": "డ్యూయల్ కనెక్షన్",
  "equalizer": "ఈక్వలైజర్",
  "equalizerImportExport": "ఈక్వలైజర్ దిగుమతి/ఎగుమతి",
  "general": "సాధారణం",
  "lights": "లైట్లు",
  "limitHighVolume": "వాల్యూమ్ పరిమితి",
  "listeningMode": "వినే మోడ్",
  "local": "స్థానికం",
  "miscellaneous": "ఇతరాలు",
  "noiseCanceling": "నాయిస్ క్యాన్సలింగ్",
  "normal": "సాధారణం",
  "soundModes": "సౌండ్ మోడ్‌లు",
  "transparency": "ట్రాన్స్‌పరెన్సీ"
 },
 "tr": {
  "acoustic": "Akustik",
  "adaptive": "Adaptif",
  "adaptiveNoiseCanceling": "Adaptif Gürültü Engelleme",
  "adaptiveNoiseCancelingSensitivityLevel": "Adaptif Gürültü Engeleme Hassasiyet Seviyesi",
  "airPressure": "Hava Basıncı",
  "airplaneMode": "Uçak Modu",
  "ambientSoundMode": "Ortam Ses Modu",
  "ancPersonalizedToEarCanal": "Kulak Kanalı için Kişiselliştirilmiş Aktif Gürültü Engelleme",
  "atmospheric": "Atmosferik",
  "autoLightsOffMinutes": "Otomatik Işık Kapatma (dakika)",
  "autoPlayPause": "Otomatik Çalma/Duraklatma",
  "autoPowerOff": "Otomatik Güç Kapatma",
  "automaticUpdate": "Otomatik Güncelleme",
  "balanced": "Dengeli",
  "bassBooster": "Bas Yükseltici",
  "bassOff": "Bass Kapalı",
  "bassReducer": "Bas Düşürücü",
  "bassUp": "BaseUp",
  "batteryLevel": "Batarya Seviyesi",
  "batteryLevelLeft": "Batarya Seviyesi (Sol)",
  "batteryLevelRight": "Batarya Seviyesi (Sağ)",
  "breathing": "Nefes",
  "bus": "Otobüs",
  "buttonConfiguration": "Buton Ayarı",
  "buttonsEnabled": "Düğmeler Aktifleştirildi",
  "car": "Araba",
  "case": "Kutu",
  "caseBatteryLevel": "Kutu Batarya Seviyesi",
  "caseFirmwareVersion": "Kutunun Yazılım Versiyonu",
  "caseLanguage": "Kutu Dili",
  "caseSerialNumber": "Kutunun Seri Numarası",
  "charging": "Sarj Oluyor",
  "classic": "Klasik",
  "classical": "Klasik",
  "connected": "Bağlandı",
  "custom": "Özel",
  "customEqualizerProfile": "Özel Profil",
  "customNoiseCanceling": "Özel Ses Engeleme",
  "customProfile": "Özel Profil",
  "dance": "Dans",
  "dbLimit": "DB Sınırı",
  "dbRefreshRate": "DB Yenileme Hızı",
  "deep": "Derin",
  "deviceInformation": "Aygıt Bilgisi",
  "disabled": "Devre Dışı",
  "disconnected": "Bağlantı Kesildi",
  "dolbyAudio": "Dolby Audio",
  "doublePress": "Çift Basış",
  "dualConnections": "Çift Bağlantılar",
  "dualConnectionsDevices": "Çift Bağlantı Aygıtları",
  "easyChat": "Kolay Konuşma",
  "easyChatWaitTime": "Kolay Konuşma Bekleme Süresi",
  "electronic": "Elektronik",
  "enabled": "Aktif",
  "environmentDetection": "Çevre Algılama",
  "equalizer": "Ekolayzer",
  "equalizerImportExport": "Ekolayzer İçe/Dışa Aktar",
  "exportCustomEqualizerProfiles": "Özel Profilleri Dışa Aktar",
  "exportCustomEqualizerProfilesOutput": "Özel Profil Dışa Aktarılım Çıktısı",
  "findDevice": "Cihazı Bul",
  "firmest": "En Sert",
  "firmwareVersion": "Cihaz Yazılımı Sürümü",
  "firmwareVersionLeft": "Cihaz Yazılımı Sürümü (Sol)",
  "firmwareVersionRight": "Cihaz Yazılımı Sürümü (Sağ)",
  "fixed": "Sabit",
  "flash": "Flaş",
  "flat": "Düz",
  "fullyTransparent": "Tamamen Şeffaf",
  "gaming": "Oyun",
  "gamingMode": "Oyun Modu",
  "general": "Genel",
  "headTracking": "Kafa Takibi",
  "heavy": "Ağır",
  "highNoise": "Yüksek Sesli Gürültü",
  "hipHop": "Hip-Hop",
  "hostDevice": "Ana Aygıt",
  "immersiveExperience": "Gerçekçi Deneyim",
  "importCustomEqualizerProfiles": "Özel Profilleri Aktar",
  "importCustomEqualizerProfilesConfirm": "Bu, aynı adı paylaşan mevcut profillerin üzerine yazılacaktır.",
  "indoor": "İç Mekan",
  "isCharging": "Sarj Oluyor Mu",
  "isChargingLeft": "Sarj Oluyor Mu (Sol)",
  "isChargingRight": "Sarj Oluyor Mu (Sağ)",
  "jazz": "Caz",
  "latin": "Latin",
  "ldac": "LDAC",
  "left": "Sol",
  "leftDoublePress": "Sola Çift Basış",
  "leftLongPress": "Sola Uzun Basış",
  "leftSinglePress": "Sola Tek Basış",
  "leftSlideDown": "Sol Sürgü Aşağı",
  "leftSlideUp": "Sol Sürgü Yukarı",
  "leftTriplePress": "Sola Üçlü Basış",
  "lightOn": "Işıkı Aç",
  "lights": "Işıklar",
  "lightsBrightness": "Renkli Işıkların Parlaklığı",
  "lightsColor": "Renkli Işıkların Renki",
  "lightsEnabled": "Renkli Işıklar Aktifleştirildi",
  "lightsMode": "Renkli Işıklar Modu",
  "limitHighVolume": "Yüksek Sesi Sınırla",
  "limitHighVolumeDbLimit": "DB Sınırı",
  "limitHighVolumeRefreshRate": "DB Yenileme Hızı",
  "listeningMode": "Dinleme modu",
  "local": "Yerel",
  "lounge": "Hol",
  "lowBatteryPrompt": "Düşük Pil Uyarı Sesi",
  "lowNoise": "Düşük Sesli Gürültü",
  "manual": "Manuel",
  "manualNoiseCanceling": "Manuel Gürültü Engeleme",
  "manualTransparency": "Manuel Şeffaflık",
  "manualUpdate": "Manuel Güncelleme",
  "medium": "Orta",
  "mediumNoise": "Orta Sesli Gürültü",
  "miscellaneous": "Çeşitli",
  "moderate": "Makul",
  "movie": "Film",
  "movieMode": "Film Modu",
  "multiScene": "Çoklu-Sahne",
  "multiSceneNoiseCanceling": "Çoklu-Sahne Gürültü Engeleme",
  "music": "Müzik",
  "musicFollows": "Müziği Takip Et",
  "nextSong": "Sonraki Şarkı",
  "no": "Hayır",
  "noiseCanceling": "Gürültü Engeleme",
  "noiseCancelingMode": "Gürültü Engelleme Modu",
  "noiseCancelingModeInCycle": "Devirde Gürültü Engeliyicisi Mod",
  "none": "Hiçbiri",
  "normal": "Normal",
  "normalModeInCycle": "Devirde Normal Mod",
  "notCharging": "Sarj Olmuyor",
  "original": "Orijinal",
  "outdoor": "Dış Mekan",
  "piano": "Piyano",
  "plane": "Uçak",
  "playPause": "Oynat / Durdur",
  "podcast": "Podcast",
  "pop": "Pop",
  "powerOff": "Güçü Kapat",
  "presetEqualizerProfile": "Ayar Profili",
  "presetProfile": "Ayar Profili",
  "pressureSensitivity": "Basınç Duyarlılığı",
  "previousSong": "Önceki Şarkı",
  "realTime": "Gerçek Zamanlı",
  "realTimeAdaptiveNoiseCanceling": "Eş Zamanlı Adaptif Gürültü Engelleme",
  "remoteCamera": "Uzaktan Kamera",
  "resetButtonsToDefault": "Butonları Varsayılana Sıfırla",
  "right": "Sağ",
  "rightDoublePress": "Sağa Çift Basış",
  "rightLongPress": "Sağa Uzun Basış",
  "rightSinglePress": "Sağa Tek Basış",
  "rightSlideDown": "Sağ Sürgü Aşağı",
  "rightSlideUp": "Sağ Sürgü Yukarı",
  "rightTriplePress": "Sağa Üçlü Basış",
  "rnb": "R&B",
  "rock": "Rock",
  "sendPacket": "Paket Gönder",
  "serialNumber": "Seri Numarası",
  "sideTone": "Yan Ses",
  "singlePress": "Tek Basış",
  "smallSpeakers": "Küçük Hoparlörler",
  "softest": "En Yumuşak",
  "soundLeakCompensation": "Ses Sızıntısı Dengeleme",
  "soundModes": "Ses Modları",
  "spatialAudio": "Çevresel Ses",
  "spatialAudioMode": "Çevresel Ses Modu",
  "spatialAudioMusicMode": "Çevresel Ses Müzik Modu",
  "spokenWord": "Söylenen Söz",
  "stateUpdatePacket": "Durum Güncelemesi Paketi",
  "strong": "Güçlü",
  "surroundSound": "Çevresel Ses",
  "talkMode": "Konuşma Modu",
  "touchLock": "Dokunma Kilidi",
  "touchTone": "Dokunma Sesi",
  "train": "Tren",
  "transparency": "Şeffaflık",
  "transparencyMode": "Şeffaflık Modu",
  "transparencyModeInCycle": "Devirde Şeffaflık Mod",
  "transport": "Aktar",
  "transportation": "Ulaşım Araçları",
  "transportationMode": "Ulaşım Aracı Modları",
  "trebleBooster": "Tiz Yükseltici",
  "trebleReducer": "Tiz Düşürücü",
  "twsStatus": "True Wireless (TWS) Durumu",
  "vocalMode": "Vokal Mod",
  "voice": "Ses",
  "voiceAssistant": "Sesli Asistan",
  "voicePrompt": "Sesli Komut",
  "volume": "Ses seviyesi",
  "volumeAdjustments": "Ses Seviyesi Değişimleri",
  "volumeBalance": "Ses Dengesi",
  "volumeBooster": "Ses Arttırıcı",
  "volumeDown": "Ses Azaltma",
  "volumeUp": "Ses Atırma",
  "weak": "Zayıf",
  "wearingDetection": "Giyilme Algılama",
  "wearingTone": "Takma Sesi",
  "windNoiseDetected": "Rüzgar Gürültüsü Tespit Edildi",
  "windNoiseSuppression": "Rüzgar Gürültüsü Azaltma",
  "yes": "Evet"
 },
 "tt": {
  "ambientSoundMode": "Тирә-як тавышы режимы",
  "buttonConfiguration": "Төймәләр көйләүләре",
  "case": "Корылау футляры",
  "deviceInformation": "Җайланма турында мәгълүмат",
  "dualConnections": "Икеләтә тоташу",
  "equalizer": "Эквалайзер",
  "equalizerImportExport": "Эквалайзер импорты/экспорты",
  "general": "Гомуми",
  "lights": "Яктырту",
  "limitHighVolume": "Тавыш көчен чикләү",
  "listeningMode": "Тыңлау режимы",
  "local": "Җирле",
  "miscellaneous": "Төрле",
  "noiseCanceling": "Шау-шуны басу",
  "normal": "Гадәти",
  "soundModes": "Тавыш режимнары",
  "transparency": "Үтәли ишетү"
 },
 "uk": {
  "acoustic": "Акустичний",
  "adaptive": "Адаптивний",
  "adaptiveNoiseCanceling": "Адаптивне шумозаглушення",
  "adaptiveNoiseCancelingSensitivityLevel": "Рівень чутливості адаптивного шумозаглушення",
  "ambientSoundMode": "Режим навколишнього звуку",
  "ancPersonalizedToEarCanal": "ANC персоналізований до слухового каналу",
  "autoPlayPause": "Автовідтворення/Пауза",
  "autoPowerOff": "Автовимкнення",
  "bassBooster": "Підсилення басів",
  "bassOff": "Бас вимкнено",
  "bassReducer": "Зменшення басів",
  "bassUp": "Посилення басів",
  "batteryLevel": "Рівень заряду",
  "batteryLevelLeft": "Рівень заряду (лівий)",
  "batteryLevelRight": "Рівень заряду (правий)",
  "bus": "Автобус",
  "buttonConfiguration": "Налаштування кнопок",
  "car": "Автомобіль",
  "case": "Зарядний кейс",
  "caseBatteryLevel": "Рівень заряду кейсу",
  "charging": "Зарядка",
  "classic": "Класичний",
  "classical": "Класика",
  "connected": "Підключено",
  "custom": "Власні",
  "customEqualizerProfile": "Користувацький профіль",
  "customNoiseCanceling": "Користувацьке шумозаглушення",
  "customProfile": "Користувацький профіль",
  "dance": "Танцювальна",
  "dbLimit": "Ліміт дБ",
  "dbRefreshRate": "Частота оновлення дБ",
  "deep": "Глибока",
  "deviceInformation": "Інформація про пристрій",
  "disabled": "Вимкнено",
  "disconnected": "Відключено",
  "dolbyAudio": "Dolby Audio",
  "doublePress": "Подвійне натискання",
  "dualConnections": "Підключення до двох пристроїв",
  "dualConnectionsDevices": "Підключені пристрої",
  "electronic": "Електронна",
  "enabled": "Увімкнено",
  "environmentDetection": "Виявлення середовища",
  "equalizer": "Еквалайзер",
  "equalizerImportExport": "Імпорт/експорт еквалайзера",
  "exportCustomEqualizerProfiles": "Експортувати користувацькі профілі",
  "exportCustomEqualizerProfilesOutput": "Експорт користувацьких профілів",
  "firmest": "Найжорсткіший",
  "firmwareVersion": "Версія прошивки",
  "firmwareVersionLeft": "Версія прошивки (ліва)",
  "firmwareVersionRight": "Версія прошивки (права)",
  "flat": "Нейтральна",
  "fullyTransparent": "Повністю прозорий",
  "gamingMode": "Ігровий режим",
  "general": "Загальне",
  "heavy": "Важкий",
  "highNoise": "Високий шум",
  "hipHop": "Хіп-хоп",
  "hostDevice": "Хост-пристрій",
  "immersiveExperience": "Повне занурення",
  "importCustomEqualizerProfiles": "Імпортувати користувацькі профілі",
  "importCustomEqualizerProfilesConfirm": "Це перезапише існуючі профілі з однаковими назвами.",
  "indoor": "Приміщення",
  "isCharging": "Заряджається",
  "isChargingLeft": "Заряджається (лівий)",
  "isChargingRight": "Заряджається (правий)",
  "jazz": "Джаз",
  "latin": "Латина",
  "ldac": "LDAC",
  "left": "Лівий",
  "leftDoublePress": "Подвійне натискання (лівий)",
  "leftLongPress": "Довге натискання (лівий)",
  "leftSinglePress": "Одне натискання (лівий)",
  "leftTriplePress": "Потрійне натискання (лівий)",
  "lights": "Підсвічування",
  "limitHighVolume": "Обмежити високу гучність",
  "limitHighVolumeDbLimit": "Ліміт дБ",
  "limitHighVolumeRefreshRate": "Частота оновлення дБ",
  "listeningMode": "Режим прослуховування",
  "local": "Локально",
  "lounge": "Лаунж",
  "lowBatteryPrompt": "Попередження про низький заряд",
  "lowNoise": "Низький шум",
  "manual": "Ручний",
  "manualNoiseCanceling": "Ручне шумозаглушення",
  "manualTransparency": "Ручна прозорість",
  "medium": "Середній",
  "mediumNoise": "Середній шум",
  "miscellaneous": "Різне",
  "moderate": "Помірний",
  "movie": "Кіно",
  "movieMode": "Кінорежим",
  "multiScene": "Мульти-сцена",
  "multiSceneNoiseCanceling": "Мульти-сцена шумозаглушення",
  "music": "Музика",
  "nextSong": "Наступна пісня",
  "no": "Ні",
  "noiseCanceling": "Шумозаглушення",
  "noiseCancelingMode": "Режим шумозаглушення",
  "noiseCancelingModeInCycle": "Режим шумозаглушення у циклі",
  "none": "Немає",
  "normal": "Нормальний",
  "normalModeInCycle": "Нормальний режим у циклі",
  "notCharging": "Не заряджається",
  "original": "Оригінальний",
  "outdoor": "На вулиці",
  "piano": "Фортепіано",
  "plane": "Літак",
  "playPause": "Відтворення/Пауза",
  "podcast": "Подкаст",
  "pop": "Поп",
  "powerOff": "Вимкнення",
  "presetEqualizerProfile": "Профіль попереднього налаштування",
  "presetProfile": "Профіль попереднього налаштування",
  "pressureSensitivity": "Чутливість до тиску",
  "previousSong": "Попередня пісня",
  "realTime": "Реальний час",
  "resetButtonsToDefault": "Скинути кнопки до стандартних",
  "right": "Правий",
  "rightDoublePress": "Подвійне натискання (правий)",
  "rightLongPress": "Довге натискання (правий)",
  "rightSinglePress": "Одне натискання (правий)",
  "rightTriplePress": "Потрійне натискання (правий)",
  "rnb": "Ритм і блюз",
  "rock": "Рок",
  "sendPacket": "Надіслати пакет",
  "serialNumber": "Серійний номер",
  "sideTone": "Самопрослуховування",
  "singlePress": "Одне натискання",
  "smallSpeakers": "Маленькі колонки",
  "softest": "Найм'якший",
  "soundLeakCompensation": "Компенсація витоку звуку",
  "soundModes": "Звукові режими",
  "spokenWord": "Мовлення",
  "stateUpdatePacket": "Пакет оновлення стану",
  "strong": "Сильний",
  "surroundSound": "Об'ємний звук",
  "talkMode": "Режим розмови",
  "touchLock": "Блокування дотику",
  "touchTone": "Звук дотику",
  "train": "Потяг",
  "transparency": "Прозорість",
  "transparencyMode": "Режим прозорості",
  "transparencyModeInCycle": "Режим прозорості у циклі",
  "transport": "Транспорт",
  "transportation": "Транспорт",
  "transportationMode": "Режим транспорту",
  "trebleBooster": "Підвищення високих",
  "trebleReducer": "Зменшення високих",
  "twsStatus": "Статус True Wireless (TWS)",
  "vocalMode": "Голосовий режим",
  "voice": "Голос",
  "voiceAssistant": "Голосовий помічник",
  "voicePrompt": "Голосова підказка",
  "volume": "Гучність",
  "volumeAdjustments": "Налаштування гучності",
  "volumeDown": "Тихіше",
  "volumeUp": "Гучніше",
  "weak": "Слабкий",
  "wearingDetection": "Виявлення носіння",
  "wearingTone": "Звук під час надягання",
  "windNoiseDetected": "Виявлено шум вітру",
  "windNoiseSuppression": "Придушення шуму вітру",
  "yes": "Так"
 },
 "vi": {
  "ambientSoundMode": "Chế độ âm thanh xung quanh",
  "buttonConfiguration": "Cấu hình nút",
  "case": "Hộp sạc",
  "deviceInformation": "Thông tin thiết bị",
  "dualConnections": "Kết nối kép",
  "equalizer": "Bộ cân bằng",
  "equalizerImportExport": "Nhập/xuất bộ cân bằng",
  "general": "Chung",
  "lights": "Đèn",
  "limitHighVolume": "Giới hạn âm lượng",
  "listeningMode": "Chế độ nghe",
  "local": "Cục bộ",
  "miscellaneous": "Khác",
  "noiseCanceling": "Chống ồn",
  "normal": "Bình thường",
  "soundModes": "Chế độ âm thanh",
  "transparency": "Xuyên âm"
 },
 "zh_CN": {
  "ambientSoundMode": "环境音模式",
  "buttonConfiguration": "按键设置",
  "case": "充电盒",
  "deviceInformation": "设备信息",
  "dualConnections": "双设备连接",
  "equalizer": "均衡器",
  "equalizerImportExport": "均衡器导入/导出",
  "general": "常规",
  "lights": "灯光",
  "limitHighVolume": "音量限制",
  "listeningMode": "聆听模式",
  "local": "本地",
  "miscellaneous": "其他",
  "noiseCanceling": "降噪",
  "normal": "普通",
  "soundModes": "声音模式",
  "transparency": "通透"
 },
 "zh_HK": {
  "ambientSoundMode": "環境音模式",
  "buttonConfiguration": "按鍵設定",
  "case": "充電盒",
  "deviceInformation": "裝置資訊",
  "dualConnections": "雙裝置連線",
  "equalizer": "等化器",
  "equalizerImportExport": "等化器匯入/匯出",
  "general": "一般",
  "lights": "燈光",
  "limitHighVolume": "音量限制",
  "listeningMode": "聆聽模式",
  "local": "本機",
  "miscellaneous": "其他",
  "noiseCanceling": "降噪",
  "normal": "一般",
  "soundModes": "聲音模式",
  "transparency": "通透"
 },
 "zh_TW": {
  "ambientSoundMode": "環境音模式",
  "buttonConfiguration": "按鍵設定",
  "case": "充電盒",
  "deviceInformation": "裝置資訊",
  "dualConnections": "雙裝置連線",
  "equalizer": "等化器",
  "equalizerImportExport": "等化器匯入/匯出",
  "general": "一般",
  "lights": "燈光",
  "limitHighVolume": "音量限制",
  "listeningMode": "聆聽模式",
  "local": "本機",
  "miscellaneous": "其他",
  "noiseCanceling": "降噪",
  "normal": "一般",
  "soundModes": "聲音模式",
  "transparency": "通透"
 }
}

// Phone language -> key in `names`: "pt_BR" and "zh_TW" first, then "pt"/"zh",
// then English. Norwegian may be reported as "no" or "nb".
var _langCache = null
function _lang() {
    if (_langCache !== null) return _langCache
    var full = Qt.locale().name              // e.g. "de_DE", "pt_BR", "zh_HK"
    var short = full.substring(0, 2)
    if (short === "no") short = "nb"
    if (names[full]) _langCache = full
    else if (names[short]) _langCache = short
    else _langCache = "en"
    return _langCache
}

// "ambientSoundMode" -> "Ambient sound mode"
function prettify(id) {
    if (!id) return ""
    var s = String(id).replace(/([a-z0-9])([A-Z])/g, "$1 $2").toLowerCase()
    return s.charAt(0).toUpperCase() + s.slice(1)
}

function name(id) {
    var l = _lang()
    if (names[l][id]) return names[l][id]
    if (names.en[id]) return names.en[id]
    return prettify(id)
}

// Corrections of mistakes in OpenSCQ30's own translation files
(function() {
    var fixes = {
        // es: "listening-mode" had the same text as "ambient-sound-mode"
        es: { listeningMode: "Modo de escucha",
              defaultListeningMode: "Modo de escucha predeterminado" },
        // fr: plural agreement
        fr: { soundModes: "Modes sonores" }
    }
    for (var l in fixes)
        for (var k in fixes[l])
            names[l][k] = fixes[l][k]
})()

// The openscq30 CLI never selects a language, so the "localizedOptions" it
// returns are always English. Translate them back via the English text:
// "Noise Canceling" -> key noiseCanceling -> "Geräuschunterdrückung".
var _englishToKey = null
function translateText(text) {
    if (typeof text !== "string" || text.length === 0) return text
    var l = _lang()
    if (l === "en") return text
    // "30 minutes" / "1 minute": untranslated in all OpenSCQ30 languages.
    // German gets words, every other language the international "min".
    var min = /^(\d+)\s+minutes?$/i.exec(text)
    if (min)
        return l === "de" ? min[1] + (parseInt(min[1]) === 1 ? " Minute" : " Minuten")
                          : min[1] + " min"
    if (_englishToKey === null) {
        _englishToKey = {}
        for (var k in names.en)
            if (_englishToKey[names.en[k]] === undefined) _englishToKey[names.en[k]] = k
    }
    var key = _englishToKey[text]
    return (key !== undefined && names[l][key]) ? names[l][key] : text
}

// Makes a setting value readable for labels.
function formatValue(value) {
    if (value === undefined || value === null || value === "") return "\u2013"
    if (typeof value === "boolean") return value ? "\u2713" : "\u2717"
    if (Array.isArray(value)) return value.join(", ")
    return String(value)
}

// ---- device form factors (for the illustrations) ------------------------

var _overEar = ["SoundcoreA3004", "SoundcoreA3027", "SoundcoreA3028", "SoundcoreA3029",
                "SoundcoreA3030", "SoundcoreA3031", "SoundcoreA3033", "SoundcoreA3035",
                "SoundcoreA3040", "SoundcoreA3062"]
var _speaker = ["SoundcoreA3116"]

// "inear" | "overear" | "speaker"
function formFactor(modelId) {
    if (_overEar.indexOf(modelId) >= 0) return "overear"
    if (_speaker.indexOf(modelId) >= 0) return "speaker"
    return "inear"
}

// Image file for a model; large=true shows earbuds in their charging case.
function deviceImage(modelId, large) {
    var f = formFactor(modelId)
    return (large && f === "inear") ? "case" : f
}

// Finds the model whose name matches a Bluetooth device name (or "").
function guessModel(bluetoothName, modelNames) {
    if (!bluetoothName || !modelNames) return ""
    var bt = String(bluetoothName).toLowerCase()
    var best = "", bestLength = 0
    for (var id in modelNames) {
        var name = String(modelNames[id]).toLowerCase()
        if ((bt.indexOf(name) >= 0 || name.indexOf(bt) >= 0) && name.length > bestLength) {
            best = id
            bestLength = name.length
        }
    }
    return best
}

// ---- battery ------------------------------------------------------------

// The CLI reports battery levels as "level/max", e.g. "4/5" -> 80
function batteryPercent(value) {
    var m = /^(\d+)\s*\/\s*(\d+)$/.exec(String(value))
    if (!m || parseInt(m[2]) === 0) return -1
    // some OpenSCQ30 modules add an offset of 1 to the level: never show more than 100 %
    return Math.max(0, Math.min(100, Math.round(parseInt(m[1]) * 100 / parseInt(m[2]))))
}

// Yes/no values: the CLI reports e.g. the charging state as "Yes"/"No"
// (not "true"/"false"). Returns true, false, or null if it is not a yes/no value.
function yesNo(value) {
    if (value === true || value === false) return value
    var v = String(value).toLowerCase()
    if (v === "true" || v === "yes") return true
    if (v === "false" || v === "no") return false
    return null
}

// "4/5" -> { level: 4, max: 5 } (or null). Many devices only report 5 steps.
function batteryLevel(value) {
    var m = /^(\d+)\s*\/\s*(\d+)$/.exec(String(value))
    if (!m || parseInt(m[2]) === 0) return null
    var max = parseInt(m[2])
    return { level: Math.max(0, Math.min(max, parseInt(m[1]))), max: max }
}

// Readable text for read-only values: battery levels as percent, single-word
// values from the CLI ("Connected", "Left", ...) translated if possible.
function formatInformation(settingId, value) {
    if (/battery/i.test(settingId)) {
        var p = batteryPercent(value)
        if (p >= 0) return p + " %"
    }
    if (typeof value === "string" && /^[A-Za-z]+$/.test(value)) {
        var key = value.charAt(0).toLowerCase() + value.slice(1)
        var l = _lang()
        if (names[l][key]) return names[l][key]
    }
    return formatValue(value)
}

// ---- additions to the upstream translations ------------------------------
// German names missing in OpenSCQ30's openscq30-lib.ftl (plus one typo fix).
(function() {
    var de = {
        limitHighVolume: "Lautstärkebegrenzung",
        limitHighVolumeDbLimit: "dB-Grenze",
        limitHighVolumeRefreshRate: "dB-Aktualisierungsrate",
        soundLeakCompensation: "Klangverlust-Ausgleich",
        surroundSound: "Surround-Sound",
        autoPlayPause: "Automatische Wiedergabe/Pause",
        wearingTone: "Trageton",
        touchLock: "Berührungssperre",
        lowBatteryPrompt: "Hinweis bei schwachem Akku",
        wearingDetection: "Trageerkennung",
        importCustomEqualizerProfiles: "Benutzerdefinierte Profile importieren",
        exportCustomEqualizerProfilesOutput: "Exportierte Profile",
        realTime: "Echtzeit",
        // new in OpenSCQ30 2.9.0
        "case": "Ladehülle",
        leftSlideUp: "Nach oben wischen links",
        leftSlideDown: "Nach unten wischen links",
        rightSlideUp: "Nach oben wischen rechts",
        rightSlideDown: "Nach unten wischen rechts",
        airplaneMode: "Flugmodus",
        atmospheric: "Atmosphäre",
        remoteCamera: "Kamera-Fernauslöser",
        findDevice: "Gerät finden",
        spatialAudio: "Räumliches Audio",
        spatialAudioMode: "Modus für räumliches Audio",
        spatialAudioMusicMode: "Musikmodus für räumliches Audio",
        caseLanguage: "Sprache der Ladehülle",
        caseSerialNumber: "Seriennummer der Ladehülle",
        caseFirmwareVersion: "Firmware-Version der Ladehülle",
        airPressure: "Luftdruck",
        easyChat: "Easy Chat",
        easyChatWaitTime: "Easy-Chat-Wartezeit",
        dualConnections: "Doppelverbindung",
        dualConnectionsDevices: "Verbundene Geräte",
        // new in OpenSCQ30 2.10 – 2.12
        lights: "Beleuchtung",
        realTimeAdaptiveNoiseCanceling: "Adaptive Geräuschunterdrückung in Echtzeit",
        volumeBalance: "Lautstärkebalance",
        lightsEnabled: "Farbige Beleuchtung",
        lightsBrightness: "Helligkeit der Beleuchtung",
        lightsColor: "Farbe der Beleuchtung",
        lightsMode: "Beleuchtungsmodus",
        autoLightsOffMinutes: "Beleuchtung automatisch aus (Minuten)",
        buttonsEnabled: "Tasten aktiviert",
        autoPowerOffPrompt: "Hinweis vor dem Ausschalten",
        listeningModePrompt: "Ansage des Hörmodus",
        incomingCallsDuringBluetoothMode: "Anrufe im Bluetooth-Modus",
        noiseCancelingPrompt: "Ansage der Geräuschunterdrückung",
        autoStopTimer: "Automatischer Stopp-Timer",
        autoStopTimerDuration: "Dauer des Stopp-Timers",
        alarms: "Wecker",
        listeningMode: "Hörmodus",
        defaultListeningMode: "Standard-Hörmodus",
        // not translated in OpenSCQ30's German file
        normalModeInCycle: "Normal-Modus im Tastenwechsel",
        transparencyModeInCycle: "Transparenz-Modus im Tastenwechsel",
        noiseCancelingModeInCycle: "Geräuschunterdrückung im Tastenwechsel",
        twsStatus: "True-Wireless-Status (TWS)",
        multiSceneNoiseCanceling: "Geräuschunterdrückung für verschiedene Umgebungen",
        transportationMode: "Verkehrsmittel-Modus",
        voicePrompt: "Sprachansagen",
        ancPersonalizedToEarCanal: "An den Gehörgang angepasste Geräuschunterdrückung",
        immersiveExperience: "Immersives Klangerlebnis",
        powerOff: "Ausschalten",
        sideTone: "Mithörton",
        dolbyAudio: "Dolby Audio",
        ldac: "LDAC",
        // option values missing in OpenSCQ30's German file
        automaticUpdate: "Automatisch aktualisieren",
        balanced: "Ausgewogen",
        bassOff: "Bass aus",
        bassUp: "Bass verstärkt",
        bloom: "Aufblühen",
        bluetooth: "Bluetooth",
        breathing: "Atmen",
        changeMode: "Modus wechseln",
        classic: "Klassik",
        dbLimit: "dB-Grenze",
        dbRefreshRate: "dB-Aktualisierungsrate",
        deep: "Tief",
        enabled: "Aktiviert",
        firmest: "Am festesten",
        fixed: "Fest",
        flash: "Blitzen",
        flat: "Neutral",
        friday: "Freitag",
        gaming: "Gaming",
        glow: "Leuchten",
        headTracking: "Kopfverfolgung",
        heavy: "Kräftig",
        latin: "Latin",
        lightOn: "Licht an",
        local: "Lokal",
        manualUpdate: "Manuell aktualisieren",
        medium: "Mittel",
        monday: "Montag",
        movie: "Film",
        movieMode: "Filmmodus",
        multiScene: "Mehrere Umgebungen",
        music: "Musik",
        musicFollows: "Musik folgt",
        nature: "Natur",
        original: "Original",
        plane: "Flugzeug",
        pressureSensitivity: "Druckempfindlichkeit",
        rhythm: "Rhythmus",
        rnb: "R&B",
        saturday: "Samstag",
        softest: "Am weichsten",
        spokenWord: "Gesprochenes Wort",
        sunday: "Sonntag",
        talkMode: "Sprechmodus",
        thursday: "Donnerstag",
        tuesday: "Dienstag",
        voice: "Stimme",
        volumeBooster: "Lautstärkeverstärker",
        wednesday: "Mittwoch",
        // only used by OpenSCQ30's internal test device
        stateUpdatePacket: "Statuspaket",
        sendPacket: "Paket senden"
    }
    for (var k in de)
        names.de[k] = de[k]
})()

